// Ciągi — matura rozszerzona i pierwszy kontakt z analizą.
//
// Kolejność jest celowa: najpierw ciąg jako funkcja i monotoniczność, bo to
// jedyne narzędzie, które przenosi się dalej bez zmian; potem dwa ciągi
// specjalne; potem szereg geometryczny, który jest pierwszym w szkole
// przejściem granicznym; potem granice na serio; procent składany jako
// zastosowanie ciągu geometrycznego; i na końcu zadania z parametrem, które
// mieszają wszystko powyżej i są tym, co faktycznie stoi w arkuszu.
//
// Cała notacja jest dobrana pod renderer z public/js/tex.js: bez środowisk
// (\begin{...} jest połykane), bez \bigl/\bigr, a \text{} tylko jednowyrazowe,
// bo tokenizer zjada spacje. To samo renderuje się poprawnie w KaTeX.
export default {
  id: 'ciagi',
  track: 'matura',
  order: 40,
  title: { pl: 'Ciągi', en: 'Sequences' },
  blurb: {
    pl: 'Od definicji ciągu i rekurencji, przez ciąg arytmetyczny i geometryczny, szereg zbieżny i procent składany, aż po granice ciągów i zadania z parametrem.',
    en: 'From the definition of a sequence and recursion, through arithmetic and geometric sequences, convergent series and compound interest, up to limits of sequences and parameter problems.',
  },
  topics: [

    /* ═══ 1. ciąg, wzór ogólny i rekurencyjny, monotoniczność ═══════════ */
    {
      id: 'ciagi-podstawy',
      title: { pl: 'Ciąg, wzór ogólny i rekurencyjny, monotoniczność', en: 'Sequences, explicit and recursive formulas, monotonicity' },
      level: 2,
      prereq: [],
      theory: {
        pl: 'Ciąg liczbowy to funkcja określona na zbiorze liczb naturalnych dodatnich: argumentem jest numer $n$, a wartością wyraz $a_{n}$. Ciąg zadajemy wzorem ogólnym $a_{n}=f(n)$, który pozwala policzyć dowolny wyraz od razu, albo wzorem rekurencyjnym, który podaje wyraz startowy i przepis na wyraz następny z poprzedniego. Rekurencja jest naturalna w modelowaniu, ale żeby dostać $a_{100}$, trzeba przejść przez wszystkie wcześniejsze wyrazy — dlatego opłaca się umieć przejść od rekurencji do wzoru ogólnego. Monotoniczność badamy znakiem różnicy $a_{n+1}-a_{n}$, a dla ciągu o wyrazach dodatnich wygodniejsze bywa porównanie ilorazu $\\frac{a_{n+1}}{a_{n}}$ z jedynką. Decydujące jest słowo „dla każdego $n$": sprawdzenie kilku pierwszych wyrazów nie dowodzi niczego, a przy ilorazie trzeba pamiętać, że dla wyrazów ujemnych nierówność się odwraca. Ciąg jest ograniczony, gdy wszystkie wyrazy mieszczą się między dwiema stałymi; ograniczoność i monotoniczność są niezależne, ale razem gwarantują zbieżność. Numer wyrazu jest liczbą naturalną, więc każde równanie na $n$ kończy się odrzuceniem rozwiązań, które nią nie są.',
        en: 'A numerical sequence is a function defined on the positive integers: the argument is the index $n$, the value is the term $a_{n}$. We define a sequence either by an explicit formula $a_{n}=f(n)$, which gives any term immediately, or by a recursive formula, which supplies a starting term and a rule producing the next term from the previous one. Recursion is natural for modelling, but to reach $a_{100}$ you must pass through every earlier term — which is why it pays to be able to turn a recursion into an explicit formula. We test monotonicity by the sign of the difference $a_{n+1}-a_{n}$, and for a sequence with positive terms it is often easier to compare the ratio $\\frac{a_{n+1}}{a_{n}}$ with one. The decisive words are "for every $n$": checking the first few terms proves nothing, and with the ratio you must remember that for negative terms the inequality reverses. A sequence is bounded when all its terms lie between two constants; boundedness and monotonicity are independent, but together they guarantee convergence. An index is a natural number, so every equation in $n$ ends with rejecting the solutions that are not.',
      },
      formulas: [
        {
          id: 'ciag-wzor-ogolny',
          tex: 'a_{n}=f(n),\\qquad n\\in\\mathbb{N}_{+}',
          name: { pl: 'Wzór ogólny ciągu', en: 'Explicit formula of a sequence' },
          note: { pl: 'Podstawiamy numer $n$, nie zmienną $x$ — $n$ przebiega tylko liczby naturalne dodatnie, więc wykres ciągu to zbiór punktów, a nie krzywa.', en: 'We substitute the index $n$, not a variable $x$ — $n$ runs only over positive integers, so the graph of a sequence is a set of points, not a curve.' },
          drill: true,
        },
        {
          id: 'ciag-rekurencja',
          tex: 'a_{1}=c,\\qquad a_{n+1}=g(a_{n})',
          name: { pl: 'Wzór rekurencyjny', en: 'Recursive formula' },
          note: { pl: 'Bez podania wyrazu startowego ciąg nie jest wyznaczony — sam przepis $a_{n+1}=g(a_{n})$ opisuje całą rodzinę ciągów.', en: 'Without a starting term the sequence is not determined — the rule $a_{n+1}=g(a_{n})$ alone describes a whole family of sequences.' },
          drill: true,
        },
        {
          id: 'monotonicznosc-roznicowa',
          tex: '\\forall n\\in\\mathbb{N}_{+}:\\ a_{n+1}-a_{n}>0\\iff (a_{n})\\ \\text{rosnacy}',
          name: { pl: 'Kryterium różnicowe monotoniczności', en: 'Difference criterion for monotonicity' },
          note: { pl: 'Nierówność musi zachodzić dla każdego $n$; sprawdzenie $a_{1}<a_{2}<a_{3}$ nie jest dowodem. Dla malejącego zmieniamy znak, dla niemalejącego dopuszczamy równość.', en: 'The inequality must hold for every $n$; checking $a_{1}<a_{2}<a_{3}$ is not a proof. For decreasing reverse the sign, for non-decreasing allow equality.' },
          drill: true,
        },
        {
          id: 'monotonicznosc-ilorazowa',
          tex: 'a_{n}>0:\\qquad \\frac{a_{n+1}}{a_{n}}>1\\iff (a_{n})\\ \\text{rosnacy}',
          name: { pl: 'Kryterium ilorazowe monotoniczności', en: 'Ratio criterion for monotonicity' },
          note: { pl: 'Wolno stosować wyłącznie przy wszystkich wyrazach dodatnich. Przy wyrazach ujemnych dzielenie odwraca nierówność i wniosek wychodzi odwrotny.', en: 'Applicable only when all terms are positive. With negative terms the division reverses the inequality and the conclusion comes out backwards.' },
          drill: true,
        },
        {
          id: 'ciag-homograficzny-roznica',
          tex: 'a_{n}=\\frac{an+b}{cn+d}\\ \\Rightarrow\\ a_{n+1}-a_{n}=\\frac{ad-bc}{(cn+d)(cn+c+d)}',
          name: { pl: 'Monotoniczność ciągu homograficznego', en: 'Monotonicity of a homographic sequence' },
          note: { pl: 'Przy dodatnim mianowniku o wszystkim decyduje znak wyznacznika $ad-bc$ — nie trzeba upraszczać całego wyrażenia, wystarczy policzyć licznik.', en: 'With a positive denominator everything is decided by the sign of the determinant $ad-bc$ — there is no need to simplify the whole expression, computing the numerator suffices.' },
          drill: true,
        },
        {
          id: 'ciag-ograniczony',
          tex: '\\exists\\, m,M\\in\\mathbb{R}\\ \\ \\forall n\\in\\mathbb{N}_{+}:\\ m\\le a_{n}\\le M',
          name: { pl: 'Ciąg ograniczony', en: 'Bounded sequence' },
          note: { pl: 'Ograniczoność nie wynika z monotoniczności: $a_{n}=n$ jest rosnący i nieograniczony. Kres górny nie musi być wyrazem ciągu.', en: 'Boundedness does not follow from monotonicity: $a_{n}=n$ is increasing and unbounded. The supremum need not be a term of the sequence.' },
          drill: true,
        },
      ],
      skills: [
        { id: 'oblicz-wyrazy-ze-wzoru', title: { pl: 'Obliczanie wyrazów ze wzoru ogólnego', en: 'Computing terms from an explicit formula' }, levels: [1, 2] },
        { id: 'wyrazy-z-rekurencji', title: { pl: 'Wyznaczanie wyrazów z rekurencji', en: 'Computing terms from a recursion' }, levels: [1, 2, 3] },
        { id: 'wzor-ogolny-z-rekurencji', title: { pl: 'Od rekurencji do wzoru ogólnego', en: 'From recursion to explicit formula' }, levels: [3, 4] },
        { id: 'badanie-monotonicznosci', title: { pl: 'Badanie monotoniczności ciągu', en: 'Testing monotonicity of a sequence' }, levels: [2, 3, 4] },
        { id: 'ciag-ograniczonosc', title: { pl: 'Ograniczoność ciągu i kresy', en: 'Boundedness of a sequence and its bounds' }, levels: [3, 4] },
        { id: 'numer-wyrazu', title: { pl: 'Wyznaczanie numeru wyrazu', en: 'Finding the index of a term' }, levels: [2, 3] },
      ],
      problems: [
        {
          id: 'ciagi-podstawy-l1-01',
          skill: 'oblicz-wyrazy-ze-wzoru',
          level: 1,
          prompt: { pl: 'Ciąg $(a_{n})$ jest określony wzorem $a_{n}=\\frac{n^{2}-3n}{n+1}$ dla $n\\ge 1$. Oblicz $a_{5}$.', en: 'The sequence $(a_{n})$ is given by $a_{n}=\\frac{n^{2}-3n}{n+1}$ for $n\\ge 1$. Compute $a_{5}$.' },
          answer: '\\frac{5}{3}',
          accept: ['1\\frac{2}{3}', '\\frac{10}{6}'],
          solution: [
            { pl: 'Podstawiamy $n=5$ w całym wyrażeniu, licznik i mianownik naraz.', en: 'Substitute $n=5$ into the whole expression, numerator and denominator at once.' },
            { pl: '$a_{5}=\\frac{5^{2}-3\\cdot 5}{5+1}=\\frac{25-15}{6}=\\frac{10}{6}$.', en: '$a_{5}=\\frac{5^{2}-3\\cdot 5}{5+1}=\\frac{25-15}{6}=\\frac{10}{6}$.' },
            { pl: 'Skracamy przez $2$: $a_{5}=\\frac{5}{3}$.', en: 'Cancel by $2$: $a_{5}=\\frac{5}{3}$.' },
          ],
          trap: { pl: 'Podstawienie $n=5$ tylko w liczniku i pozostawienie $n+1$ w mianowniku, albo „skrócenie" $\\frac{n^{2}-3n}{n+1}$ przez $n$ — mianownik nie jest iloczynem, więc nic tu skrócić nie można.', en: 'Substituting $n=5$ only in the numerator and leaving $n+1$ below, or "cancelling" $\\frac{n^{2}-3n}{n+1}$ by $n$ — the denominator is not a product, so nothing cancels.' },
        },
        {
          id: 'ciagi-podstawy-l2-02',
          skill: 'wyrazy-z-rekurencji',
          level: 2,
          prompt: { pl: 'Ciąg $(a_{n})$ jest określony rekurencyjnie: $a_{1}=2$ oraz $a_{n+1}=2a_{n}-3$ dla $n\\ge 1$. Oblicz $a_{4}$.', en: 'The sequence $(a_{n})$ is defined recursively by $a_{1}=2$ and $a_{n+1}=2a_{n}-3$ for $n\\ge 1$. Compute $a_{4}$.' },
          answer: '-5',
          accept: [],
          solution: [
            { pl: '$a_{2}=2\\cdot 2-3=1$.', en: '$a_{2}=2\\cdot 2-3=1$.' },
            { pl: '$a_{3}=2\\cdot 1-3=-1$.', en: '$a_{3}=2\\cdot 1-3=-1$.' },
            { pl: '$a_{4}=2\\cdot(-1)-3=-5$.', en: '$a_{4}=2\\cdot(-1)-3=-5$.' },
          ],
          trap: { pl: 'Odczytanie rekurencji wstecz, czyli liczenie $a_{n}=2a_{n+1}-3$, oraz start od $a_{0}$ — indeksowanie zaczyna się tu od $1$, więc do $a_{4}$ prowadzą dokładnie trzy kroki.', en: 'Reading the recursion backwards, i.e. computing $a_{n}=2a_{n+1}-3$, and starting from $a_{0}$ — indexing here starts at $1$, so exactly three steps lead to $a_{4}$.' },
        },
        {
          id: 'ciagi-podstawy-l2-03',
          skill: 'numer-wyrazu',
          level: 2,
          prompt: { pl: 'Ciąg $(a_{n})$ jest określony wzorem $a_{n}=n^{2}-2n-8$. Sprawdź, czy liczba $7$ jest wyrazem tego ciągu, a jeśli tak — podaj jego numer.', en: 'The sequence $(a_{n})$ is given by $a_{n}=n^{2}-2n-8$. Check whether $7$ is a term of this sequence and, if so, give its index.' },
          answer: 'n=5',
          accept: ['a_{5}=7', '5'],
          solution: [
            { pl: 'Rozwiązujemy $n^{2}-2n-8=7$, czyli $n^{2}-2n-15=0$.', en: 'Solve $n^{2}-2n-8=7$, i.e. $n^{2}-2n-15=0$.' },
            { pl: '$\\Delta=4+60=64$, $\\sqrt{\\Delta}=8$, więc $n=\\frac{2-8}{2}=-3$ lub $n=\\frac{2+8}{2}=5$.', en: '$\\Delta=4+60=64$, $\\sqrt{\\Delta}=8$, so $n=\\frac{2-8}{2}=-3$ or $n=\\frac{2+8}{2}=5$.' },
            { pl: 'Numer wyrazu musi być liczbą naturalną dodatnią, więc $n=-3$ odrzucamy. Zostaje $n=5$ i istotnie $a_{5}=25-10-8=7$.', en: 'An index must be a positive integer, so $n=-3$ is rejected. This leaves $n=5$, and indeed $a_{5}=25-10-8=7$.' },
          ],
          trap: { pl: 'Podanie obu pierwiastków równania kwadratowego jako odpowiedzi — $n=-3$ nie jest numerem wyrazu, bo dziedziną ciągu jest $\\mathbb{N}_{+}$, a nie $\\mathbb{R}$.', en: 'Giving both roots of the quadratic as the answer — $n=-3$ is not an index, because the domain of a sequence is $\\mathbb{N}_{+}$, not $\\mathbb{R}$.' },
        },
        {
          id: 'ciagi-podstawy-l3-04',
          skill: 'badanie-monotonicznosci',
          level: 3,
          prompt: { pl: 'Wykaż, że ciąg $a_{n}=\\frac{3n-1}{n+2}$ jest rosnący.', en: 'Show that the sequence $a_{n}=\\frac{3n-1}{n+2}$ is increasing.' },
          answer: 'a_{n+1}-a_{n}=\\frac{7}{(n+2)(n+3)}>0',
          accept: ['\\frac{7}{(n+2)(n+3)}>0', 'ciag rosnacy, bo roznica jest dodatnia dla kazdego n'],
          solution: [
            { pl: 'Liczymy $a_{n+1}=\\frac{3(n+1)-1}{(n+1)+2}=\\frac{3n+2}{n+3}$.', en: 'Compute $a_{n+1}=\\frac{3(n+1)-1}{(n+1)+2}=\\frac{3n+2}{n+3}$.' },
            { pl: 'Sprowadzamy różnicę do wspólnego mianownika: $a_{n+1}-a_{n}=\\frac{(3n+2)(n+2)-(3n-1)(n+3)}{(n+3)(n+2)}$.', en: 'Bring the difference to a common denominator: $a_{n+1}-a_{n}=\\frac{(3n+2)(n+2)-(3n-1)(n+3)}{(n+3)(n+2)}$.' },
            { pl: 'W liczniku $(3n^{2}+8n+4)-(3n^{2}+8n-3)=7$, więc $a_{n+1}-a_{n}=\\frac{7}{(n+2)(n+3)}$.', en: 'In the numerator $(3n^{2}+8n+4)-(3n^{2}+8n-3)=7$, so $a_{n+1}-a_{n}=\\frac{7}{(n+2)(n+3)}$.' },
            { pl: 'Dla $n\\ge 1$ mianownik jest dodatni, więc różnica jest dodatnia dla każdego $n$ i ciąg jest rosnący.', en: 'For $n\\ge 1$ the denominator is positive, so the difference is positive for every $n$ and the sequence is increasing.' },
          ],
          trap: { pl: 'Policzenie $a_{1},a_{2},a_{3}$, zauważenie wzrostu i uznanie sprawy za zamkniętą — to nie jest dowód. Drugi błąd to skrócenie ułamka $\\frac{3n-1}{n+2}$ „do $3$" i wniosek, że ciąg jest stały.', en: 'Computing $a_{1},a_{2},a_{3}$, noticing growth and calling it done — that is not a proof. The second error is "cancelling" $\\frac{3n-1}{n+2}$ down to $3$ and concluding the sequence is constant.' },
        },
        {
          id: 'ciagi-podstawy-l3-05',
          skill: 'badanie-monotonicznosci',
          level: 3,
          prompt: { pl: 'Dany jest ciąg $a_{n}=\\frac{n}{2^{n}}$. Wykaż, że jest on nierosnący, i wyznacz wszystkie $n$, dla których $a_{n+1}=a_{n}$.', en: 'Given the sequence $a_{n}=\\frac{n}{2^{n}}$, show that it is non-increasing and find all $n$ for which $a_{n+1}=a_{n}$.' },
          answer: 'n=1',
          accept: ['\\frac{a_{n+1}}{a_{n}}=\\frac{n+1}{2n},\\ n=1'],
          solution: [
            { pl: 'Wszystkie wyrazy są dodatnie, więc wolno użyć kryterium ilorazowego.', en: 'All terms are positive, so the ratio criterion may be used.' },
            { pl: '$\\frac{a_{n+1}}{a_{n}}=\\frac{n+1}{2^{n+1}}\\cdot\\frac{2^{n}}{n}=\\frac{n+1}{2n}$.', en: '$\\frac{a_{n+1}}{a_{n}}=\\frac{n+1}{2^{n+1}}\\cdot\\frac{2^{n}}{n}=\\frac{n+1}{2n}$.' },
            { pl: 'Nierówność $\\frac{n+1}{2n}\\le 1$ jest równoważna $n+1\\le 2n$, czyli $n\\ge 1$ — zachodzi dla każdego $n$, więc ciąg jest nierosnący.', en: 'The inequality $\\frac{n+1}{2n}\\le 1$ is equivalent to $n+1\\le 2n$, i.e. $n\\ge 1$ — true for every $n$, so the sequence is non-increasing.' },
            { pl: 'Równość $\\frac{n+1}{2n}=1$ daje $n=1$; istotnie $a_{1}=\\frac{1}{2}=a_{2}$, a dla $n\\ge 2$ ciąg jest już ściśle malejący.', en: 'Equality $\\frac{n+1}{2n}=1$ gives $n=1$; indeed $a_{1}=\\frac{1}{2}=a_{2}$, and for $n\\ge 2$ the sequence is strictly decreasing.' },
          ],
          trap: { pl: 'Napisanie, że ciąg jest malejący — jest tylko nierosnący, bo $a_{1}=a_{2}=\\frac{1}{2}$. Nierówność ostra $\\frac{n+1}{2n}<1$ nie zachodzi dla $n=1$ i właśnie ten jeden przypadek zadanie sprawdza.', en: 'Writing that the sequence is decreasing — it is only non-increasing, since $a_{1}=a_{2}=\\frac{1}{2}$. The strict inequality $\\frac{n+1}{2n}<1$ fails at $n=1$, and that single case is what the problem tests.' },
        },
        {
          id: 'ciagi-podstawy-l3-06',
          skill: 'wzor-ogolny-z-rekurencji',
          level: 3,
          prompt: { pl: 'Ciąg $(a_{n})$ spełnia warunki $a_{1}=3$ oraz $a_{n+1}=a_{n}+4n$ dla $n\\ge 1$. Wyznacz wzór ogólny tego ciągu.', en: 'The sequence $(a_{n})$ satisfies $a_{1}=3$ and $a_{n+1}=a_{n}+4n$ for $n\\ge 1$. Find its explicit formula.' },
          answer: 'a_{n}=2n^{2}-2n+3',
          accept: ['2n(n-1)+3', 'a_{n}=3+2n(n-1)'],
          solution: [
            { pl: 'Sumujemy równości teleskopowo: $a_{n}=a_{1}+\\sum\\limits_{k=1}^{n-1}4k$, bo przejść od $a_{1}$ do $a_{n}$ jest $n-1$.', en: 'Sum the identities telescopically: $a_{n}=a_{1}+\\sum\\limits_{k=1}^{n-1}4k$, since there are $n-1$ steps from $a_{1}$ to $a_{n}$.' },
            { pl: 'Korzystamy z $1+2+\\dots+(n-1)=\\frac{(n-1)n}{2}$, więc $\\sum\\limits_{k=1}^{n-1}4k=4\\cdot\\frac{(n-1)n}{2}=2n(n-1)$.', en: 'Using $1+2+\\dots+(n-1)=\\frac{(n-1)n}{2}$, we get $\\sum\\limits_{k=1}^{n-1}4k=4\\cdot\\frac{(n-1)n}{2}=2n(n-1)$.' },
            { pl: 'Stąd $a_{n}=3+2n(n-1)=2n^{2}-2n+3$.', en: 'Hence $a_{n}=3+2n(n-1)=2n^{2}-2n+3$.' },
            { pl: 'Sprawdzenie: $a_{1}=3$, $a_{2}=8-4+3=7=a_{1}+4\\cdot 1$, $a_{3}=18-6+3=15=a_{2}+4\\cdot 2$.', en: 'Check: $a_{1}=3$, $a_{2}=8-4+3=7=a_{1}+4\\cdot 1$, $a_{3}=18-6+3=15=a_{2}+4\\cdot 2$.' },
          ],
          trap: { pl: 'Sumowanie do $n$ zamiast do $n-1$ — daje $a_{n}=2n^{2}+2n+3$, wzór, który nie spełnia nawet $a_{1}=3$. Zawsze warto sprawdzić wynik na pierwszym wyrazie.', en: 'Summing up to $n$ instead of $n-1$ — this yields $a_{n}=2n^{2}+2n+3$, a formula that fails even $a_{1}=3$. Always test the result on the first term.' },
        },
        {
          id: 'ciagi-podstawy-l4-07',
          skill: 'ciag-ograniczonosc',
          level: 4,
          prompt: { pl: 'Wykaż, że ciąg $a_{n}=\\frac{4n+1}{n+3}$ jest ograniczony, i podaj jego kres dolny oraz kres górny.', en: 'Show that the sequence $a_{n}=\\frac{4n+1}{n+3}$ is bounded and give its infimum and supremum.' },
          answer: '\\frac{5}{4}\\le a_{n}<4',
          accept: ['\\inf a_{n}=\\frac{5}{4},\\ \\sup a_{n}=4', 'kres dolny 5/4 (osiagany), kres gorny 4 (nieosiagany)'],
          solution: [
            { pl: 'Wykonujemy dzielenie: $a_{n}=\\frac{4(n+3)-11}{n+3}=4-\\frac{11}{n+3}$.', en: 'Divide out: $a_{n}=\\frac{4(n+3)-11}{n+3}=4-\\frac{11}{n+3}$.' },
            { pl: 'Dla $n\\ge 1$ mamy $\\frac{11}{n+3}>0$, więc $a_{n}<4$ dla każdego $n$.', en: 'For $n\\ge 1$ we have $\\frac{11}{n+3}>0$, so $a_{n}<4$ for every $n$.' },
            { pl: 'Ciąg $\\frac{11}{n+3}$ jest malejący, więc $a_{n}$ jest rosnący i najmniejszy jest wyraz pierwszy: $a_{1}=\\frac{5}{4}$.', en: 'The sequence $\\frac{11}{n+3}$ is decreasing, so $a_{n}$ is increasing and the smallest term is the first: $a_{1}=\\frac{5}{4}$.' },
            { pl: 'Zatem $\\frac{5}{4}\\le a_{n}<4$: kres dolny to $\\frac{5}{4}$ i jest osiągany, kres górny to $4$ i nie jest osiągany.', en: 'Hence $\\frac{5}{4}\\le a_{n}<4$: the infimum is $\\frac{5}{4}$ and is attained, the supremum is $4$ and is not attained.' },
          ],
          trap: { pl: 'Zapisanie $a_{n}\\le 4$ i twierdzenie, że $4$ jest największym wyrazem ciągu. Kres górny nie musi należeć do zbioru wartości — tutaj $a_{n}=4$ nie zachodzi dla żadnego $n$.', en: 'Writing $a_{n}\\le 4$ and claiming $4$ is the greatest term. A supremum need not belong to the set of values — here $a_{n}=4$ holds for no $n$.' },
        },
        {
          id: 'ciagi-podstawy-l4-08',
          skill: 'wzor-ogolny-z-rekurencji',
          level: 4,
          prompt: { pl: 'Ciąg $(a_{n})$ dany jest wzorem rekurencyjnym $a_{1}=1$, $a_{n+1}=3a_{n}+2$ dla $n\\ge 1$. Wyznacz wzór ogólny tego ciągu.', en: 'The sequence $(a_{n})$ is given by $a_{1}=1$, $a_{n+1}=3a_{n}+2$ for $n\\ge 1$. Find its explicit formula.' },
          answer: 'a_{n}=2\\cdot 3^{n-1}-1',
          accept: ['\\frac{2}{3}\\cdot 3^{n}-1', 'a_{n}=\\frac{2\\cdot 3^{n}-3}{3}'],
          solution: [
            { pl: 'Szukamy stałej $c$ takiej, że podstawienie $b_{n}=a_{n}+c$ usunie wyraz wolny: z $a_{n+1}+c=3(a_{n}+c)$ dostajemy $c=3c-2$, czyli $c=1$.', en: 'Look for a constant $c$ such that the substitution $b_{n}=a_{n}+c$ removes the constant term: from $a_{n+1}+c=3(a_{n}+c)$ we get $c=3c-2$, i.e. $c=1$.' },
            { pl: 'Dla $b_{n}=a_{n}+1$ mamy $b_{n+1}=a_{n+1}+1=3a_{n}+3=3b_{n}$, więc $(b_{n})$ jest geometryczny o ilorazie $3$.', en: 'For $b_{n}=a_{n}+1$ we get $b_{n+1}=a_{n+1}+1=3a_{n}+3=3b_{n}$, so $(b_{n})$ is geometric with ratio $3$.' },
            { pl: '$b_{1}=a_{1}+1=2$, zatem $b_{n}=2\\cdot 3^{n-1}$.', en: '$b_{1}=a_{1}+1=2$, hence $b_{n}=2\\cdot 3^{n-1}$.' },
            { pl: 'Wracamy: $a_{n}=b_{n}-1=2\\cdot 3^{n-1}-1$. Sprawdzenie: $a_{1}=1$, $a_{2}=5=3\\cdot 1+2$, $a_{3}=17=3\\cdot 5+2$.', en: 'Return: $a_{n}=b_{n}-1=2\\cdot 3^{n-1}-1$. Check: $a_{1}=1$, $a_{2}=5=3\\cdot 1+2$, $a_{3}=17=3\\cdot 5+2$.' },
          ],
          trap: { pl: 'Uznanie ciągu za geometryczny o ilorazie $3$ i napisanie $a_{n}=3^{n-1}$ — stała $+2$ psuje geometryczność, bo $\\frac{a_{2}}{a_{1}}=5$, a $\\frac{a_{3}}{a_{2}}=\\frac{17}{5}$. Dopiero przesunięcie $b_{n}=a_{n}+1$ czyni ciąg geometrycznym.', en: 'Treating the sequence as geometric with ratio $3$ and writing $a_{n}=3^{n-1}$ — the constant $+2$ destroys the geometric property, since $\\frac{a_{2}}{a_{1}}=5$ while $\\frac{a_{3}}{a_{2}}=\\frac{17}{5}$. Only the shift $b_{n}=a_{n}+1$ makes it geometric.' },
        },
      ],
    },

    /* ═══ 2. ciąg arytmetyczny ═══════════════════════════════════════════ */
    {
      id: 'ciag-arytmetyczny',
      title: { pl: 'Ciąg arytmetyczny', en: 'Arithmetic sequence' },
      level: 2,
      prereq: ['ciagi-podstawy'],
      theory: {
        pl: 'Ciąg jest arytmetyczny, gdy różnica dwóch kolejnych wyrazów jest stała: $a_{n+1}-a_{n}=r$ dla każdego $n$. Wtedy $a_{n}=a_{1}+(n-1)r$ — mnożnikiem jest $n-1$, bo od pierwszego do $n$-tego wyrazu robimy $n-1$ kroków, i to jest najczęściej gubiony szczegół całego działu. Sumę $n$ początkowych wyrazów liczymy jak Gauss: dodając ciąg do siebie zapisanego wspak, dostajemy $n$ jednakowych par, skąd $S_{n}=\\frac{a_{1}+a_{n}}{2}\\cdot n$. Po podstawieniu $a_{n}=a_{1}+(n-1)r$ widać, że $S_{n}$ jest funkcją kwadratową zmiennej $n$ bez wyrazu wolnego — i odwrotnie, jeśli $S_{n}=An^{2}+Bn$, to ciąg jest arytmetyczny o różnicy $r=2A$. Własność środkowego wyrazu, $a_{n}=\\frac{a_{n-1}+a_{n+1}}{2}$, jest warunkiem koniecznym i wystarczającym: trzy liczby tworzą ciąg arytmetyczny dokładnie wtedy, gdy środkowa jest średnią arytmetyczną skrajnych. To ona zamienia zadania z parametrem w jedno równanie. Gdy $r<0$, suma $S_{n}$ ma maksimum — osiąga je na ostatnim nieujemnym wyrazie, a nie w wierzchołku paraboli, bo $n$ musi być liczbą naturalną.',
        en: 'A sequence is arithmetic when the difference of two consecutive terms is constant: $a_{n+1}-a_{n}=r$ for every $n$. Then $a_{n}=a_{1}+(n-1)r$ — the multiplier is $n-1$, because going from the first to the $n$-th term takes $n-1$ steps, and this is the most frequently lost detail in the whole topic. We compute the sum of the first $n$ terms the way Gauss did: adding the sequence to its own reversal gives $n$ identical pairs, whence $S_{n}=\\frac{a_{1}+a_{n}}{2}\\cdot n$. Substituting $a_{n}=a_{1}+(n-1)r$ shows that $S_{n}$ is a quadratic function of $n$ with no constant term — and conversely, if $S_{n}=An^{2}+Bn$, the sequence is arithmetic with difference $r=2A$. The middle-term property, $a_{n}=\\frac{a_{n-1}+a_{n+1}}{2}$, is a necessary and sufficient condition: three numbers form an arithmetic sequence exactly when the middle one is the arithmetic mean of the outer two. It is what turns parameter problems into a single equation. When $r<0$ the sum $S_{n}$ has a maximum — attained at the last non-negative term, not at the vertex of the parabola, because $n$ must be a natural number.',
      },
      formulas: [
        {
          id: 'arytm-definicja',
          tex: 'a_{n+1}-a_{n}=r\\qquad \\forall n\\in\\mathbb{N}_{+}',
          name: { pl: 'Definicja ciągu arytmetycznego', en: 'Definition of an arithmetic sequence' },
          note: { pl: 'Różnica musi być ta sama dla każdego $n$ — sprawdzenie jednej pary wyrazów niczego nie dowodzi. Dowodząc arytmetyczności, liczymy $a_{n+1}-a_{n}$ ogólnie i pokazujemy, że nie zależy od $n$.', en: 'The difference must be the same for every $n$ — checking one pair of terms proves nothing. To prove a sequence is arithmetic, compute $a_{n+1}-a_{n}$ in general and show it does not depend on $n$.' },
          drill: true,
        },
        {
          id: 'arytm-n-ty',
          tex: 'a_{n}=a_{1}+(n-1)r',
          name: { pl: 'Wzór na $n$-ty wyraz', en: 'Formula for the $n$-th term' },
          note: { pl: 'Mnożnikiem jest $n-1$, nie $n$. Najprostszy test pamięci: dla $n=1$ wzór musi dać $a_{1}$.', en: 'The multiplier is $n-1$, not $n$. The simplest memory test: for $n=1$ the formula must return $a_{1}$.' },
          drill: true,
        },
        {
          id: 'arytm-n-ty-od-k',
          tex: 'a_{n}=a_{k}+(n-k)r',
          name: { pl: 'Wyraz $n$-ty przez wyraz $k$-ty', en: 'The $n$-th term from the $k$-th term' },
          note: { pl: 'Skraca rachunki, gdy dane są wyrazy o dalekich numerach: z $a_{3}$ i $a_{11}$ od razu $a_{11}-a_{3}=8r$, bez wyznaczania $a_{1}$.', en: 'Shortens the work when distant terms are given: from $a_{3}$ and $a_{11}$ we get $a_{11}-a_{3}=8r$ at once, without finding $a_{1}$.' },
          drill: true,
        },
        {
          id: 'arytm-suma',
          tex: 'S_{n}=\\frac{a_{1}+a_{n}}{2}\\cdot n',
          name: { pl: 'Suma $n$ początkowych wyrazów', en: 'Sum of the first $n$ terms' },
          note: { pl: 'Wersja do użycia, gdy znamy oba końce. $\\frac{a_{1}+a_{n}}{2}$ to średnia arytmetyczna wszystkich wyrazów — stąd „liczba wyrazów razy średnia".', en: 'The version to use when both ends are known. $\\frac{a_{1}+a_{n}}{2}$ is the mean of all the terms — hence "number of terms times the average".' },
          drill: true,
        },
        {
          id: 'arytm-suma-r',
          tex: 'S_{n}=\\frac{2a_{1}+(n-1)r}{2}\\cdot n',
          name: { pl: 'Suma przez $a_{1}$ i $r$', en: 'Sum in terms of $a_{1}$ and $r$' },
          note: { pl: 'Wersja do użycia, gdy nie znamy $a_{n}$ — na przykład gdy $n$ jest szukaną niewiadomą i suma prowadzi do równania kwadratowego.', en: 'The version to use when $a_{n}$ is unknown — for instance when $n$ is the unknown and the sum leads to a quadratic equation.' },
          drill: true,
        },
        {
          id: 'arytm-srodkowy',
          tex: 'a_{n}=\\frac{a_{n-1}+a_{n+1}}{2}\\iff (a_{n-1},a_{n},a_{n+1})\\ \\text{arytmetyczny}',
          name: { pl: 'Własność środkowego wyrazu', en: 'Middle-term property' },
          note: { pl: 'Warunek konieczny i wystarczający — to podstawowe narzędzie w zadaniach z parametrem. Środkowy wyraz jest średnią arytmetyczną sąsiadów, więc równoważnie $2a_{n}=a_{n-1}+a_{n+1}$.', en: 'A necessary and sufficient condition — the basic tool in parameter problems. The middle term is the arithmetic mean of its neighbours, so equivalently $2a_{n}=a_{n-1}+a_{n+1}$.' },
          drill: true,
        },
        {
          id: 'arytm-suma-kwadratowa',
          tex: 'S_{n}=\\frac{r}{2}n^{2}+\\left(a_{1}-\\frac{r}{2}\\right)n',
          name: { pl: 'Suma jako funkcja kwadratowa $n$', en: 'The sum as a quadratic function of $n$' },
          note: { pl: 'Odwrotnie: jeśli $S_{n}=An^{2}+Bn$, to ciąg jest arytmetyczny i $r=2A$, $a_{1}=A+B$. Obecność wyrazu wolnego w $S_{n}$ wyklucza arytmetyczność, bo zawsze $S_{0}=0$.', en: 'Conversely: if $S_{n}=An^{2}+Bn$, the sequence is arithmetic with $r=2A$ and $a_{1}=A+B$. A constant term in $S_{n}$ rules out an arithmetic sequence, since always $S_{0}=0$.' },
          drill: true,
        },
        {
          id: 'arytm-suma-naturalnych',
          tex: '1+2+\\dots+n=\\frac{n(n+1)}{2}',
          name: { pl: 'Suma kolejnych liczb naturalnych', en: 'Sum of consecutive natural numbers' },
          note: { pl: 'Szczególny przypadek $a_{1}=r=1$. Warto go znać na pamięć — pojawia się przy sumach teleskopowych i przy granicach typu $\\frac{1+2+\\dots+n}{n^{2}}$.', en: 'The special case $a_{1}=r=1$. Worth knowing by heart — it turns up in telescoping sums and in limits of the form $\\frac{1+2+\\dots+n}{n^{2}}$.' },
          drill: true,
        },
      ],
      skills: [
        { id: 'arytm-wyrazy-i-roznica', title: { pl: 'Wyznaczanie wyrazów i różnicy', en: 'Finding terms and the common difference' }, levels: [1, 2, 3] },
        { id: 'arytm-suma-wyrazow', title: { pl: 'Suma wyrazów ciągu arytmetycznego', en: 'Sum of an arithmetic sequence' }, levels: [2, 3] },
        { id: 'arytm-uklad-rownan', title: { pl: 'Układy równań na $a_{1}$ i $r$', en: 'Systems of equations for $a_{1}$ and $r$' }, levels: [3, 4] },
        { id: 'arytm-srodkowy-wyraz', title: { pl: 'Własność środkowego wyrazu', en: 'The middle-term property' }, levels: [2, 3, 4] },
        { id: 'arytm-suma-jako-funkcja', title: { pl: 'Suma jako funkcja kwadratowa', en: 'The sum as a quadratic function' }, levels: [4, 5] },
        { id: 'arytm-zadania-tekstowe', title: { pl: 'Zadania tekstowe z ciągiem arytmetycznym', en: 'Word problems with arithmetic sequences' }, levels: [2, 3, 4] },
      ],
      problems: [
        {
          id: 'ciag-arytmetyczny-l1-01',
          skill: 'arytm-wyrazy-i-roznica',
          level: 1,
          prompt: { pl: 'W ciągu arytmetycznym $(a_{n})$ dane są $a_{1}=-7$ oraz $r=4$. Oblicz $a_{20}$.', en: 'In an arithmetic sequence $(a_{n})$ we have $a_{1}=-7$ and $r=4$. Compute $a_{20}$.' },
          answer: '69',
          accept: [],
          solution: [
            { pl: 'Ze wzoru $a_{n}=a_{1}+(n-1)r$ mamy $a_{20}=a_{1}+19r$.', en: 'From $a_{n}=a_{1}+(n-1)r$ we get $a_{20}=a_{1}+19r$.' },
            { pl: '$a_{20}=-7+19\\cdot 4=-7+76=69$.', en: '$a_{20}=-7+19\\cdot 4=-7+76=69$.' },
          ],
          trap: { pl: 'Użycie $20r$ zamiast $19r$ — od $a_{1}$ do $a_{20}$ jest dziewiętnaście kroków po $r$, a nie dwadzieścia. Błąd daje $73$.', en: 'Using $20r$ instead of $19r$ — from $a_{1}$ to $a_{20}$ there are nineteen steps of $r$, not twenty. The error gives $73$.' },
        },
        {
          id: 'ciag-arytmetyczny-l2-02',
          skill: 'arytm-suma-wyrazow',
          level: 2,
          prompt: { pl: 'Oblicz sumę wszystkich liczb dwucyfrowych podzielnych przez $7$.', en: 'Compute the sum of all two-digit numbers divisible by $7$.' },
          answer: '728',
          accept: [],
          solution: [
            { pl: 'Szukane liczby tworzą ciąg arytmetyczny o $a_{1}=14$, $r=7$ i ostatnim wyrazie $98$ (bo $105$ jest już trzycyfrowe).', en: 'The numbers form an arithmetic sequence with $a_{1}=14$, $r=7$ and last term $98$ (since $105$ already has three digits).' },
            { pl: 'Liczba wyrazów: z $98=14+(n-1)\\cdot 7$ dostajemy $n-1=12$, czyli $n=13$.', en: 'Number of terms: from $98=14+(n-1)\\cdot 7$ we get $n-1=12$, so $n=13$.' },
            { pl: '$S_{13}=\\frac{14+98}{2}\\cdot 13=56\\cdot 13=728$.', en: '$S_{13}=\\frac{14+98}{2}\\cdot 13=56\\cdot 13=728$.' },
          ],
          trap: { pl: 'Przyjęcie $n=\\frac{98-14}{7}=12$ i pominięcie dodania jedynki — liczymy odstępy, a wyrazów jest o jeden więcej. Drugi wariant tego błędu to rozpoczęcie od $7$ zamiast od $14$.', en: 'Taking $n=\\frac{98-14}{7}=12$ and forgetting to add one — that counts gaps, and there is one more term than gaps. A second version of the error is starting at $7$ instead of $14$.' },
        },
        {
          id: 'ciag-arytmetyczny-l2-03',
          skill: 'arytm-suma-wyrazow',
          level: 2,
          prompt: { pl: 'W ciągu arytmetycznym $(a_{n})$ dane są $a_{3}=8$ oraz $a_{11}=32$. Oblicz $S_{20}$.', en: 'In an arithmetic sequence $(a_{n})$ we have $a_{3}=8$ and $a_{11}=32$. Compute $S_{20}$.' },
          answer: '610',
          accept: [],
          solution: [
            { pl: 'Z $a_{11}=a_{3}+8r$ mamy $32=8+8r$, czyli $r=3$.', en: 'From $a_{11}=a_{3}+8r$ we get $32=8+8r$, so $r=3$.' },
            { pl: '$a_{1}=a_{3}-2r=8-6=2$.', en: '$a_{1}=a_{3}-2r=8-6=2$.' },
            { pl: '$S_{20}=\\frac{2a_{1}+19r}{2}\\cdot 20=\\frac{4+57}{2}\\cdot 20=61\\cdot 10=610$.', en: '$S_{20}=\\frac{2a_{1}+19r}{2}\\cdot 20=\\frac{4+57}{2}\\cdot 20=61\\cdot 10=610$.' },
          ],
          trap: { pl: 'Zapisanie $a_{11}=a_{3}+9r$ — między wyrazem trzecim a jedenastym jest $11-3=8$ różnic, nie $9$. Analogicznie $a_{1}=a_{3}-2r$, a nie $a_{3}-3r$.', en: 'Writing $a_{11}=a_{3}+9r$ — between the third and eleventh term there are $11-3=8$ differences, not $9$. Likewise $a_{1}=a_{3}-2r$, not $a_{3}-3r$.' },
        },
        {
          id: 'ciag-arytmetyczny-l3-04',
          skill: 'arytm-srodkowy-wyraz',
          level: 3,
          prompt: { pl: 'Wyznacz wszystkie wartości $x$, dla których liczby $x-1$, $x+3$, $3x+1$ tworzą w podanej kolejności ciąg arytmetyczny.', en: 'Find all $x$ for which the numbers $x-1$, $x+3$, $3x+1$ form, in this order, an arithmetic sequence.' },
          answer: 'x=3',
          accept: [],
          solution: [
            { pl: 'Z własności środkowego wyrazu: $2(x+3)=(x-1)+(3x+1)$.', en: 'By the middle-term property: $2(x+3)=(x-1)+(3x+1)$.' },
            { pl: '$2x+6=4x$, więc $2x=6$ i $x=3$.', en: '$2x+6=4x$, so $2x=6$ and $x=3$.' },
            { pl: 'Sprawdzenie: otrzymujemy $2$, $6$, $10$ — ciąg arytmetyczny o różnicy $r=4$.', en: 'Check: we obtain $2$, $6$, $10$ — an arithmetic sequence with difference $r=4$.' },
          ],
          trap: { pl: 'Przyrównanie ilorazów zamiast różnic, czyli użycie warunku geometrycznego $(x+3)^{2}=(x-1)(3x+1)$. Dla ciągu arytmetycznego środkowy wyraz jest średnią arytmetyczną, a nie geometryczną skrajnych.', en: 'Equating ratios instead of differences, i.e. using the geometric condition $(x+3)^{2}=(x-1)(3x+1)$. For an arithmetic sequence the middle term is the arithmetic, not the geometric, mean of the outer two.' },
        },
        {
          id: 'ciag-arytmetyczny-l3-05',
          skill: 'arytm-wyrazy-i-roznica',
          level: 3,
          prompt: { pl: 'W ciągu arytmetycznym $(a_{n})$ zachodzą warunki $a_{4}+a_{6}=26$ oraz $a_{3}=9$. Oblicz $a_{15}$.', en: 'In an arithmetic sequence $(a_{n})$ we have $a_{4}+a_{6}=26$ and $a_{3}=9$. Compute $a_{15}$.' },
          answer: '33',
          accept: [],
          solution: [
            { pl: 'Wyrazy $a_{4}$ i $a_{6}$ są symetryczne względem $a_{5}$, więc $a_{4}+a_{6}=2a_{5}$, skąd $a_{5}=13$.', en: 'The terms $a_{4}$ and $a_{6}$ are symmetric about $a_{5}$, so $a_{4}+a_{6}=2a_{5}$, giving $a_{5}=13$.' },
            { pl: 'Z $a_{5}=a_{3}+2r$ mamy $13=9+2r$, czyli $r=2$.', en: 'From $a_{5}=a_{3}+2r$ we get $13=9+2r$, so $r=2$.' },
            { pl: '$a_{15}=a_{5}+10r=13+20=33$.', en: '$a_{15}=a_{5}+10r=13+20=33$.' },
          ],
          trap: { pl: 'Napisanie $a_{15}=a_{5}+11r$ — od piątego do piętnastego wyrazu jest dziesięć kroków. Ten sam błąd o jeden powtarza się przy przejściu $a_{3}\\to a_{5}$.', en: 'Writing $a_{15}=a_{5}+11r$ — from the fifth to the fifteenth term there are ten steps. The same off-by-one recurs in the step $a_{3}\\to a_{5}$.' },
        },
        {
          id: 'ciag-arytmetyczny-l3-06',
          skill: 'arytm-zadania-tekstowe',
          level: 3,
          prompt: { pl: 'W teatrze jest $24$ rzędy foteli. W pierwszym rzędzie jest $18$ miejsc, a w każdym następnym o $3$ miejsca więcej niż w poprzednim. Ile miejsc jest w tym teatrze?', en: 'A theatre has $24$ rows of seats. The first row has $18$ seats and each following row has $3$ more seats than the previous one. How many seats are there in the theatre?' },
          answer: '1260',
          accept: [],
          solution: [
            { pl: 'Liczby miejsc w rzędach tworzą ciąg arytmetyczny o $a_{1}=18$ i $r=3$.', en: 'The numbers of seats per row form an arithmetic sequence with $a_{1}=18$ and $r=3$.' },
            { pl: 'W ostatnim rzędzie: $a_{24}=18+23\\cdot 3=18+69=87$.', en: 'In the last row: $a_{24}=18+23\\cdot 3=18+69=87$.' },
            { pl: '$S_{24}=\\frac{18+87}{2}\\cdot 24=\\frac{105}{2}\\cdot 24=105\\cdot 12=1260$.', en: '$S_{24}=\\frac{18+87}{2}\\cdot 24=\\frac{105}{2}\\cdot 24=105\\cdot 12=1260$.' },
          ],
          trap: { pl: 'Policzenie ostatniego rzędu jako $18+24\\cdot 3=90$ — przyrost o $3$ następuje dopiero od drugiego rzędu, więc do rzędu dwudziestego czwartego dochodzi $23$ razy.', en: 'Computing the last row as $18+24\\cdot 3=90$ — the increase of $3$ starts only from the second row, so it is added $23$ times up to row twenty-four.' },
        },
        {
          id: 'ciag-arytmetyczny-l4-07',
          skill: 'arytm-uklad-rownan',
          level: 4,
          prompt: { pl: 'W ciągu arytmetycznym $(a_{n})$ zachodzą warunki $S_{5}=40$ oraz $a_{2}\\cdot a_{4}=55$. Wyznacz $a_{1}$ i $r$.', en: 'In an arithmetic sequence $(a_{n})$ we have $S_{5}=40$ and $a_{2}\\cdot a_{4}=55$. Find $a_{1}$ and $r$.' },
          answer: 'a_{1}=2,\\ r=3\\ \\lor\\ a_{1}=14,\\ r=-3',
          accept: ['(a_{1},r)=(2,3)\\ \\lor\\ (a_{1},r)=(14,-3)'],
          solution: [
            { pl: 'Wyrazy $a_{1},\\dots,a_{5}$ są symetryczne względem $a_{3}$, więc $S_{5}=5a_{3}$, skąd $a_{3}=8$.', en: 'The terms $a_{1},\\dots,a_{5}$ are symmetric about $a_{3}$, so $S_{5}=5a_{3}$, giving $a_{3}=8$.' },
            { pl: 'Zapisujemy $a_{2}=8-r$ i $a_{4}=8+r$, więc $a_{2}a_{4}=64-r^{2}=55$.', en: 'Write $a_{2}=8-r$ and $a_{4}=8+r$, so $a_{2}a_{4}=64-r^{2}=55$.' },
            { pl: 'Stąd $r^{2}=9$, czyli $r=3$ lub $r=-3$.', en: 'Hence $r^{2}=9$, so $r=3$ or $r=-3$.' },
            { pl: 'Dla $r=3$: $a_{1}=a_{3}-2r=2$. Dla $r=-3$: $a_{1}=8+6=14$. Oba rozwiązania spełniają warunki zadania.', en: 'For $r=3$: $a_{1}=a_{3}-2r=2$. For $r=-3$: $a_{1}=8+6=14$. Both solutions satisfy the conditions.' },
          ],
          trap: { pl: 'Podanie tylko $r=3$ — z $r^{2}=9$ wynikają dwie wartości, a zadanie nie zakłada, że ciąg jest rosnący. Utrata połowy rozwiązania z $\\pm$ to najczęstsza strata punktów w tym typie zadań.', en: 'Giving only $r=3$ — $r^{2}=9$ yields two values, and nothing in the problem says the sequence is increasing. Losing half of a $\\pm$ solution is the commonest loss of marks in this type of problem.' },
        },
        {
          id: 'ciag-arytmetyczny-l4-08',
          skill: 'arytm-suma-jako-funkcja',
          level: 4,
          prompt: { pl: 'Suma $n$ początkowych wyrazów pewnego ciągu $(a_{n})$ wyraża się wzorem $S_{n}=2n^{2}+3n$ dla $n\\ge 1$. Wyznacz wzór ogólny tego ciągu i wykaż, że jest on arytmetyczny.', en: 'The sum of the first $n$ terms of a sequence $(a_{n})$ is $S_{n}=2n^{2}+3n$ for $n\\ge 1$. Find the explicit formula of the sequence and show that it is arithmetic.' },
          answer: 'a_{n}=4n+1',
          accept: ['a_{n}=4n+1,\\ a_{1}=5,\\ r=4', 'a_{1}=5,\\ r=4'],
          solution: [
            { pl: 'Dla $n\\ge 2$ zachodzi $a_{n}=S_{n}-S_{n-1}$.', en: 'For $n\\ge 2$ we have $a_{n}=S_{n}-S_{n-1}$.' },
            { pl: '$S_{n-1}=2(n-1)^{2}+3(n-1)=2n^{2}-4n+2+3n-3=2n^{2}-n-1$.', en: '$S_{n-1}=2(n-1)^{2}+3(n-1)=2n^{2}-4n+2+3n-3=2n^{2}-n-1$.' },
            { pl: '$a_{n}=(2n^{2}+3n)-(2n^{2}-n-1)=4n+1$.', en: '$a_{n}=(2n^{2}+3n)-(2n^{2}-n-1)=4n+1$.' },
            { pl: 'Osobno $a_{1}=S_{1}=5$, co zgadza się ze wzorem $4\\cdot 1+1=5$, więc wzór obowiązuje dla wszystkich $n$.', en: 'Separately $a_{1}=S_{1}=5$, which agrees with $4\\cdot 1+1=5$, so the formula holds for all $n$.' },
            { pl: 'Różnica $a_{n+1}-a_{n}=4(n+1)+1-(4n+1)=4$ jest stała, więc ciąg jest arytmetyczny o $a_{1}=5$ i $r=4$.', en: 'The difference $a_{n+1}-a_{n}=4(n+1)+1-(4n+1)=4$ is constant, so the sequence is arithmetic with $a_{1}=5$ and $r=4$.' },
          ],
          trap: { pl: 'Zastosowanie $a_{n}=S_{n}-S_{n-1}$ także dla $n=1$ bez zastrzeżenia — wzór na $S_{n}$ jest dany dopiero od $n=1$, więc pierwszy wyraz trzeba policzyć osobno jako $S_{1}$ i dopiero potem sprawdzić zgodność. Drugi błąd: uznanie, że każdy wzór kwadratowy na $S_{n}$ daje ciąg arytmetyczny — obecność wyrazu wolnego by to zepsuła, bo musi być $S_{n}\\to 0$ przy $n\\to 0$.', en: 'Applying $a_{n}=S_{n}-S_{n-1}$ at $n=1$ as well, with no caveat — the formula for $S_{n}$ is given only from $n=1$, so the first term must be computed separately as $S_{1}$ and only then checked for agreement. A second error: assuming every quadratic $S_{n}$ gives an arithmetic sequence — a constant term would spoil it, since $S_{n}$ must tend to $0$ as $n\\to 0$.' },
        },
        {
          id: 'ciag-arytmetyczny-l5-09',
          skill: 'arytm-suma-jako-funkcja',
          level: 5,
          prompt: { pl: 'W ciągu arytmetycznym $(a_{n})$ dane są $a_{1}=25$ oraz $r=-3$. Wyznacz $n$, dla którego suma $S_{n}$ jest największa, i oblicz tę sumę.', en: 'In an arithmetic sequence $(a_{n})$ we have $a_{1}=25$ and $r=-3$. Find the $n$ for which the sum $S_{n}$ is greatest, and compute that sum.' },
          answer: 'n=9,\\ S_{9}=117',
          accept: ['n=9,\\ S_{n}=117', 'S_{9}=117'],
          solution: [
            { pl: 'Suma rośnie dopóki dokładamy wyrazy nieujemne, więc szukamy ostatniego $n$ z $a_{n}\\ge 0$.', en: 'The sum grows as long as we add non-negative terms, so we look for the last $n$ with $a_{n}\\ge 0$.' },
            { pl: '$a_{n}=25-3(n-1)=28-3n\\ge 0$ daje $n\\le \\frac{28}{3}=9\\frac{1}{3}$, czyli $n\\le 9$.', en: '$a_{n}=25-3(n-1)=28-3n\\ge 0$ gives $n\\le \\frac{28}{3}=9\\frac{1}{3}$, i.e. $n\\le 9$.' },
            { pl: 'Sprawdzenie: $a_{9}=1>0$, a $a_{10}=-2<0$, więc maksimum przypada na $n=9$.', en: 'Check: $a_{9}=1>0$ while $a_{10}=-2<0$, so the maximum is at $n=9$.' },
            { pl: '$S_{9}=\\frac{a_{1}+a_{9}}{2}\\cdot 9=\\frac{25+1}{2}\\cdot 9=13\\cdot 9=117$.', en: '$S_{9}=\\frac{a_{1}+a_{9}}{2}\\cdot 9=\\frac{25+1}{2}\\cdot 9=13\\cdot 9=117$.' },
          ],
          trap: { pl: 'Potraktowanie $S_{n}=\\frac{53n-3n^{2}}{2}$ jak funkcji zmiennej rzeczywistej i przyjęcie wierzchołka $n=\\frac{53}{6}\\approx 8{,}83$, a potem zaokrąglenie w dół do $n=8$. Wierzchołek nie jest liczbą naturalną, więc trzeba porównać $S_{8}=116$ i $S_{9}=117$ — większa jest ta druga.', en: 'Treating $S_{n}=\\frac{53n-3n^{2}}{2}$ as a function of a real variable, taking the vertex $n=\\frac{53}{6}\\approx 8.83$ and rounding down to $n=8$. The vertex is not a natural number, so one must compare $S_{8}=116$ with $S_{9}=117$ — the latter is larger.' },
        },
      ],
    },

    /* ═══ 3. ciąg geometryczny ═══════════════════════════════════════════ */
    {
      id: 'ciag-geometryczny',
      title: { pl: 'Ciąg geometryczny', en: 'Geometric sequence' },
      level: 3,
      prereq: ['ciagi-podstawy'],
      theory: {
        pl: 'Ciąg jest geometryczny, gdy iloraz dwóch kolejnych wyrazów jest stały: $\\frac{a_{n+1}}{a_{n}}=q$. Warunek ten wymusza, że żaden wyraz nie jest zerem i że $q\\neq 0$ — o tym założeniu trzeba pamiętać, bo to ono odrzuca fałszywe rozwiązania w zadaniach z parametrem. Wzór na wyraz $n$-ty to $a_{n}=a_{1}q^{\\,n-1}$, znów z wykładnikiem $n-1$, a suma $n$ początkowych wyrazów wynosi $S_{n}=a_{1}\\cdot\\frac{1-q^{n}}{1-q}$ — wzór ten jest bezużyteczny dla $q=1$ i wtedy po prostu $S_{n}=na_{1}$. Własność środkowego wyrazu przyjmuje postać $a_{n}^{2}=a_{n-1}a_{n+1}$; uwaga, kwadrat, a nie średnia, więc wyciągając pierwiastek dostajemy $|a_{n}|$ i znak trzeba rozstrzygnąć osobno. Monotoniczność zależy od znaku $a_{1}$ i położenia $q$ względem $1$, przy czym dla $q<0$ ciąg jest naprzemienny i nie jest monotoniczny w ogóle. Iloraz ujemny jest całkowicie legalny i odrzucanie go „bo wygląda dziwnie" jest częstym błędem. W zadaniach z dwoma warunkami układ zwykle sprowadza się do równania kwadratowego na $q$, które prawie zawsze ma dwa rozwiązania i oba trzeba sprawdzić.',
        en: 'A sequence is geometric when the ratio of two consecutive terms is constant: $\\frac{a_{n+1}}{a_{n}}=q$. This forces every term to be non-zero and $q\\neq 0$ — an assumption worth remembering, since it is what rejects spurious solutions in parameter problems. The $n$-th term is $a_{n}=a_{1}q^{\\,n-1}$, again with exponent $n-1$, and the sum of the first $n$ terms is $S_{n}=a_{1}\\cdot\\frac{1-q^{n}}{1-q}$ — useless for $q=1$, where simply $S_{n}=na_{1}$. The middle-term property becomes $a_{n}^{2}=a_{n-1}a_{n+1}$; note the square, not a mean, so taking a root gives $|a_{n}|$ and the sign must be settled separately. Monotonicity depends on the sign of $a_{1}$ and the position of $q$ relative to $1$, and for $q<0$ the sequence alternates and is not monotone at all. A negative ratio is entirely legitimate, and discarding it "because it looks odd" is a common error. In problems with two conditions the system usually reduces to a quadratic in $q$, which almost always has two solutions, both of which must be checked.',
      },
      formulas: [
        {
          id: 'geom-definicja',
          tex: '\\frac{a_{n+1}}{a_{n}}=q,\\qquad a_{n}\\neq 0,\\ q\\neq 0',
          name: { pl: 'Definicja ciągu geometrycznego', en: 'Definition of a geometric sequence' },
          note: { pl: 'Żaden wyraz ciągu geometrycznego nie może być zerem — inaczej iloraz byłby nieokreślony. To założenie odrzuca część pierwiastków w zadaniach z parametrem.', en: 'No term of a geometric sequence may be zero — otherwise the ratio would be undefined. This assumption rejects some roots in parameter problems.' },
          drill: true,
        },
        {
          id: 'geom-n-ty',
          tex: 'a_{n}=a_{1}q^{\\,n-1}',
          name: { pl: 'Wzór na $n$-ty wyraz', en: 'Formula for the $n$-th term' },
          note: { pl: 'Wykładnik to $n-1$, nie $n$. Przy ujemnym $q$ parzystość wykładnika decyduje o znaku wyrazu — stąd naprzemienność.', en: 'The exponent is $n-1$, not $n$. With negative $q$ the parity of the exponent decides the sign of the term — hence the alternation.' },
          drill: true,
        },
        {
          id: 'geom-n-ty-od-k',
          tex: 'a_{n}=a_{k}q^{\\,n-k}',
          name: { pl: 'Wyraz $n$-ty przez wyraz $k$-ty', en: 'The $n$-th term from the $k$-th term' },
          note: { pl: 'Z $a_{2}$ i $a_{5}$ od razu $a_{5}=a_{2}q^{3}$ — wykładnikiem jest różnica numerów, czyli $3$, a nie $4$.', en: 'From $a_{2}$ and $a_{5}$ we get $a_{5}=a_{2}q^{3}$ at once — the exponent is the difference of indices, i.e. $3$, not $4$.' },
          drill: true,
        },
        {
          id: 'geom-suma',
          tex: 'S_{n}=a_{1}\\cdot\\frac{1-q^{n}}{1-q},\\qquad q\\neq 1',
          name: { pl: 'Suma $n$ początkowych wyrazów', en: 'Sum of the first $n$ terms' },
          note: { pl: 'Kolejność odejmowania musi być zgodna w liczniku i mianowniku — $\\frac{q^{n}-1}{q-1}$ jest tym samym wyrażeniem, ale mieszanka $\\frac{1-q^{n}}{q-1}$ daje wynik z odwrotnym znakiem.', en: 'The order of subtraction must match in numerator and denominator — $\\frac{q^{n}-1}{q-1}$ is the same expression, but the mixture $\\frac{1-q^{n}}{q-1}$ gives the opposite sign.' },
          drill: true,
        },
        {
          id: 'geom-suma-q1',
          tex: 'q=1\\ \\Rightarrow\\ S_{n}=n\\,a_{1}',
          name: { pl: 'Suma przy ilorazie równym $1$', en: 'Sum when the ratio equals $1$' },
          note: { pl: 'Przypadek do rozpatrzenia osobno zawsze, gdy $q$ jest niewiadomą lub zależy od parametru — wzór ogólny ma wtedy zero w mianowniku.', en: 'A case to be handled separately whenever $q$ is unknown or depends on a parameter — the general formula then has zero in the denominator.' },
          drill: true,
        },
        {
          id: 'geom-srodkowy',
          tex: 'a_{n}^{2}=a_{n-1}\\cdot a_{n+1}',
          name: { pl: 'Własność środkowego wyrazu', en: 'Middle-term property' },
          note: { pl: 'Kwadrat środkowego wyrazu, nie średnia. Z tego warunku wynika $|a_{n}|=\\sqrt{a_{n-1}a_{n+1}}$, więc znak środkowego wyrazu trzeba rozstrzygnąć osobno — bywają dwa rozwiązania.', en: 'The square of the middle term, not a mean. It gives $|a_{n}|=\\sqrt{a_{n-1}a_{n+1}}$, so the sign of the middle term must be settled separately — there are often two solutions.' },
          drill: true,
        },
        {
          id: 'geom-iloczyn-symetryczny',
          tex: 'a_{k}\\cdot a_{n-k+1}=a_{1}\\cdot a_{n}',
          name: { pl: 'Iloczyn wyrazów równo odległych od końców', en: 'Product of terms equidistant from the ends' },
          note: { pl: 'Geometryczny odpowiednik symetrii sum w ciągu arytmetycznym. Stąd iloczyn wszystkich $n$ wyrazów wynosi $(a_{1}a_{n})^{n/2}$.', en: 'The geometric counterpart of the symmetry of sums in an arithmetic sequence. Hence the product of all $n$ terms equals $(a_{1}a_{n})^{n/2}$.' },
          drill: true,
        },
        {
          id: 'geom-monotonicznosc',
          tex: 'a_{1}>0\\ \\wedge\\ q>1\\ \\Rightarrow\\ a_{n+1}>a_{n};\\qquad a_{1}>0\\ \\wedge\\ 0<q<1\\ \\Rightarrow\\ a_{n+1}<a_{n}',
          name: { pl: 'Monotoniczność ciągu geometrycznego', en: 'Monotonicity of a geometric sequence' },
          note: { pl: 'Przy $a_{1}<0$ oba wnioski się odwracają. Przy $q<0$ ciąg jest naprzemienny i nie jest monotoniczny — żadna z tych implikacji nie ma wtedy zastosowania.', en: 'For $a_{1}<0$ both conclusions reverse. For $q<0$ the sequence alternates and is not monotone — neither implication applies then.' },
          drill: true,
        },
      ],
      skills: [
        { id: 'geom-wyrazy-i-iloraz', title: { pl: 'Wyznaczanie wyrazów i ilorazu', en: 'Finding terms and the common ratio' }, levels: [1, 2, 3] },
        { id: 'geom-suma-n-wyrazow', title: { pl: 'Suma $n$ wyrazów ciągu geometrycznego', en: 'Sum of $n$ terms of a geometric sequence' }, levels: [2, 3, 4] },
        { id: 'geom-srodkowy-wyraz', title: { pl: 'Własność środkowego wyrazu', en: 'The middle-term property' }, levels: [2, 3, 4] },
        { id: 'geom-uklad-rownan', title: { pl: 'Układy równań na $a_{1}$ i $q$', en: 'Systems of equations for $a_{1}$ and $q$' }, levels: [3, 4, 5] },
        { id: 'geom-monotonicznosc-znak', title: { pl: 'Monotoniczność i znak wyrazów', en: 'Monotonicity and the sign of the terms' }, levels: [3, 4] },
        { id: 'geom-zadania-tekstowe', title: { pl: 'Zadania tekstowe z ciągiem geometrycznym', en: 'Word problems with geometric sequences' }, levels: [3, 4] },
      ],
      problems: [
        {
          id: 'ciag-geometryczny-l1-01',
          skill: 'geom-wyrazy-i-iloraz',
          level: 1,
          prompt: { pl: 'W ciągu geometrycznym $(a_{n})$ dane są $a_{1}=5$ oraz $q=-2$. Oblicz $a_{6}$.', en: 'In a geometric sequence $(a_{n})$ we have $a_{1}=5$ and $q=-2$. Compute $a_{6}$.' },
          answer: '-160',
          accept: [],
          solution: [
            { pl: 'Ze wzoru $a_{n}=a_{1}q^{\\,n-1}$ mamy $a_{6}=5\\cdot(-2)^{5}$.', en: 'From $a_{n}=a_{1}q^{\\,n-1}$ we get $a_{6}=5\\cdot(-2)^{5}$.' },
            { pl: '$(-2)^{5}=-32$, więc $a_{6}=5\\cdot(-32)=-160$.', en: '$(-2)^{5}=-32$, so $a_{6}=5\\cdot(-32)=-160$.' },
          ],
          trap: { pl: 'Podniesienie do potęgi szóstej zamiast piątej, co daje $320$, albo policzenie $(-2)^{5}$ jako $32$ — nieparzysta potęga liczby ujemnej jest ujemna.', en: 'Raising to the sixth rather than the fifth power, giving $320$, or evaluating $(-2)^{5}$ as $32$ — an odd power of a negative number is negative.' },
        },
        {
          id: 'ciag-geometryczny-l2-02',
          skill: 'geom-wyrazy-i-iloraz',
          level: 2,
          prompt: { pl: 'W ciągu geometrycznym $(a_{n})$ dane są $a_{2}=12$ oraz $a_{5}=96$. Wyznacz $a_{1}$ i $q$.', en: 'In a geometric sequence $(a_{n})$ we have $a_{2}=12$ and $a_{5}=96$. Find $a_{1}$ and $q$.' },
          answer: 'a_{1}=6,\\ q=2',
          accept: ['(a_{1},q)=(6,2)'],
          solution: [
            { pl: 'Z $a_{5}=a_{2}q^{3}$ mamy $96=12q^{3}$, czyli $q^{3}=8$.', en: 'From $a_{5}=a_{2}q^{3}$ we get $96=12q^{3}$, so $q^{3}=8$.' },
            { pl: 'Równanie $q^{3}=8$ ma w liczbach rzeczywistych jedno rozwiązanie: $q=2$.', en: 'The equation $q^{3}=8$ has one real solution: $q=2$.' },
            { pl: '$a_{1}=\\frac{a_{2}}{q}=\\frac{12}{2}=6$.', en: '$a_{1}=\\frac{a_{2}}{q}=\\frac{12}{2}=6$.' },
          ],
          trap: { pl: 'Napisanie $a_{5}=a_{2}q^{4}$ — wykładnikiem jest różnica numerów $5-2=3$. Osobno warto zauważyć, że przy nieparzystej potędze nie ma tu drugiego rozwiązania, w odróżnieniu od $q^{2}=\\dots$.', en: 'Writing $a_{5}=a_{2}q^{4}$ — the exponent is the index difference $5-2=3$. Note also that an odd power gives no second solution here, unlike $q^{2}=\\dots$.' },
        },
        {
          id: 'ciag-geometryczny-l2-03',
          skill: 'geom-suma-n-wyrazow',
          level: 2,
          prompt: { pl: 'Oblicz sumę $2+4+8+\\dots+512$.', en: 'Compute the sum $2+4+8+\\dots+512$.' },
          answer: '1022',
          accept: [],
          solution: [
            { pl: 'To ciąg geometryczny o $a_{1}=2$ i $q=2$; wyrazy to $2^{1},2^{2},\\dots,2^{9}$, bo $512=2^{9}$.', en: 'This is a geometric sequence with $a_{1}=2$ and $q=2$; the terms are $2^{1},2^{2},\\dots,2^{9}$, since $512=2^{9}$.' },
            { pl: 'Liczba wyrazów wynosi $n=9$.', en: 'The number of terms is $n=9$.' },
            { pl: '$S_{9}=2\\cdot\\frac{1-2^{9}}{1-2}=2\\cdot\\frac{-511}{-1}=1022$.', en: '$S_{9}=2\\cdot\\frac{1-2^{9}}{1-2}=2\\cdot\\frac{-511}{-1}=1022$.' },
          ],
          trap: { pl: 'Przyjęcie $n=10$ przez pomylenie wykładnika z numerem wyrazu — ciąg zaczyna się od $2^{1}$, a nie od $2^{0}$, więc $512=2^{9}$ jest wyrazem dziewiątym. Drugi wariant błędu to $n=\\frac{512}{2}=256$.', en: 'Taking $n=10$ by confusing the exponent with the index — the sequence starts at $2^{1}$, not $2^{0}$, so $512=2^{9}$ is the ninth term. Another version of the error is $n=\\frac{512}{2}=256$.' },
        },
        {
          id: 'ciag-geometryczny-l3-04',
          skill: 'geom-srodkowy-wyraz',
          level: 3,
          prompt: { pl: 'Wyznacz wszystkie wartości $x$, dla których liczby $x$, $x+4$, $4x$ tworzą w podanej kolejności ciąg geometryczny.', en: 'Find all $x$ for which the numbers $x$, $x+4$, $4x$ form, in this order, a geometric sequence.' },
          answer: 'x=4\\ \\lor\\ x=-\\frac{4}{3}',
          accept: ['x\\in\\left\\{4,-\\frac{4}{3}\\right\\}'],
          solution: [
            { pl: 'Z własności środkowego wyrazu: $(x+4)^{2}=x\\cdot 4x$.', en: 'By the middle-term property: $(x+4)^{2}=x\\cdot 4x$.' },
            { pl: '$x^{2}+8x+16=4x^{2}$, czyli $3x^{2}-8x-16=0$.', en: '$x^{2}+8x+16=4x^{2}$, i.e. $3x^{2}-8x-16=0$.' },
            { pl: '$\\Delta=64+192=256$, $\\sqrt{\\Delta}=16$, więc $x=\\frac{8+16}{6}=4$ lub $x=\\frac{8-16}{6}=-\\frac{4}{3}$.', en: '$\\Delta=64+192=256$, $\\sqrt{\\Delta}=16$, so $x=\\frac{8+16}{6}=4$ or $x=\\frac{8-16}{6}=-\\frac{4}{3}$.' },
            { pl: 'Sprawdzamy, że żaden wyraz nie jest zerem. Dla $x=4$: $4,8,16$ i $q=2$. Dla $x=-\\frac{4}{3}$: $-\\frac{4}{3},\\frac{8}{3},-\\frac{16}{3}$ i $q=-2$. Oba rozwiązania są poprawne.', en: 'Check that no term is zero. For $x=4$: $4,8,16$ with $q=2$. For $x=-\\frac{4}{3}$: $-\\frac{4}{3},\\frac{8}{3},-\\frac{16}{3}$ with $q=-2$. Both solutions are valid.' },
          ],
          trap: { pl: 'Odrzucenie $x=-\\frac{4}{3}$ jako „niepasującego", bo daje ujemny iloraz. Iloraz ciągu geometrycznego może być ujemny; zabronione jest tylko $q=0$ oraz zerowy wyraz, a tu ani jedno, ani drugie nie zachodzi.', en: 'Discarding $x=-\\frac{4}{3}$ as "not fitting" because it gives a negative ratio. The ratio of a geometric sequence may be negative; only $q=0$ and a zero term are forbidden, and neither occurs here.' },
        },
        {
          id: 'ciag-geometryczny-l3-05',
          skill: 'geom-suma-n-wyrazow',
          level: 3,
          prompt: { pl: 'W ciągu geometrycznym $(a_{n})$ o ilorazie $q=2$ suma trzech początkowych wyrazów wynosi $S_{3}=21$. Oblicz $a_{1}$ oraz $a_{5}$.', en: 'In a geometric sequence $(a_{n})$ with ratio $q=2$ the sum of the first three terms is $S_{3}=21$. Compute $a_{1}$ and $a_{5}$.' },
          answer: 'a_{1}=3,\\ a_{5}=48',
          accept: ['(a_{1},a_{5})=(3,48)'],
          solution: [
            { pl: '$S_{3}=a_{1}(1+q+q^{2})=a_{1}(1+2+4)=7a_{1}$.', en: '$S_{3}=a_{1}(1+q+q^{2})=a_{1}(1+2+4)=7a_{1}$.' },
            { pl: 'Z $7a_{1}=21$ dostajemy $a_{1}=3$.', en: 'From $7a_{1}=21$ we get $a_{1}=3$.' },
            { pl: '$a_{5}=a_{1}q^{4}=3\\cdot 16=48$.', en: '$a_{5}=a_{1}q^{4}=3\\cdot 16=48$.' },
          ],
          trap: { pl: 'Zapisanie $S_{3}=a_{1}\\frac{1-q^{3}}{q-1}$, czyli pomieszanie kolejności odejmowania w liczniku i mianowniku — wychodzi wtedy $a_{1}=-3$. Poprawnie $\\frac{1-q^{n}}{1-q}$ albo $\\frac{q^{n}-1}{q-1}$, nigdy na krzyż.', en: 'Writing $S_{3}=a_{1}\\frac{1-q^{3}}{q-1}$, i.e. mixing the order of subtraction between numerator and denominator — this yields $a_{1}=-3$. Correctly $\\frac{1-q^{n}}{1-q}$ or $\\frac{q^{n}-1}{q-1}$, never crossed.' },
        },
        {
          id: 'ciag-geometryczny-l4-06',
          skill: 'geom-monotonicznosc-znak',
          level: 4,
          prompt: { pl: 'Wyznacz wszystkie wartości ilorazu $q$, dla których ciąg geometryczny o pierwszym wyrazie $a_{1}=-3$ jest rosnący.', en: 'Find all values of the ratio $q$ for which the geometric sequence with first term $a_{1}=-3$ is increasing.' },
          answer: 'q\\in(0,1)',
          accept: ['0<q<1'],
          solution: [
            { pl: '$a_{n}=-3q^{\\,n-1}$, więc $a_{n+1}-a_{n}=-3q^{\\,n-1}(q-1)$.', en: '$a_{n}=-3q^{\\,n-1}$, so $a_{n+1}-a_{n}=-3q^{\\,n-1}(q-1)$.' },
            { pl: 'Warunek $a_{n+1}-a_{n}>0$ dla każdego $n$ jest równoważny $q^{\\,n-1}(q-1)<0$ dla każdego $n$.', en: 'The condition $a_{n+1}-a_{n}>0$ for every $n$ is equivalent to $q^{\\,n-1}(q-1)<0$ for every $n$.' },
            { pl: 'Jeśli $q<0$, to $q^{\\,n-1}$ zmienia znak wraz z parzystością $n$, więc nierówność nie może zachodzić dla wszystkich $n$ — ciąg jest naprzemienny.', en: 'If $q<0$ then $q^{\\,n-1}$ changes sign with the parity of $n$, so the inequality cannot hold for all $n$ — the sequence alternates.' },
            { pl: 'Zostaje $q>0$, a wtedy $q^{\\,n-1}>0$ i warunek redukuje się do $q-1<0$. Łącznie $q\\in(0,1)$; przypadek $q=1$ daje ciąg stały, a nie rosnący.', en: 'This leaves $q>0$, where $q^{\\,n-1}>0$ and the condition reduces to $q-1<0$. Together $q\\in(0,1)$; the case $q=1$ gives a constant, not an increasing, sequence.' },
          ],
          trap: { pl: 'Sprawdzenie warunku tylko dla $n=1$, co daje samo $q<1$ i błędnie wpuszcza wszystkie $q<0$. Przy ujemnym ilorazie ciąg skacze nad i pod zero, więc nie jest monotoniczny — trzeba jawnie założyć $q>0$.', en: 'Checking the condition only at $n=1$, which yields merely $q<1$ and wrongly admits all $q<0$. With a negative ratio the sequence jumps above and below zero, so it is not monotone — one must explicitly require $q>0$.' },
        },
        {
          id: 'ciag-geometryczny-l4-07',
          skill: 'geom-uklad-rownan',
          level: 4,
          prompt: { pl: 'W ciągu geometrycznym $(a_{n})$ zachodzą warunki $a_{1}+a_{3}=20$ oraz $a_{2}=8$. Wyznacz $a_{1}$ i $q$.', en: 'In a geometric sequence $(a_{n})$ we have $a_{1}+a_{3}=20$ and $a_{2}=8$. Find $a_{1}$ and $q$.' },
          answer: 'a_{1}=4,\\ q=2\\ \\lor\\ a_{1}=16,\\ q=\\frac{1}{2}',
          accept: ['(a_{1},q)=(4,2)\\ \\lor\\ (a_{1},q)=\\left(16,\\frac{1}{2}\\right)'],
          solution: [
            { pl: 'Zapisujemy warunki przez $a_{1}$ i $q$: $a_{1}(1+q^{2})=20$ oraz $a_{1}q=8$.', en: 'Write the conditions in terms of $a_{1}$ and $q$: $a_{1}(1+q^{2})=20$ and $a_{1}q=8$.' },
            { pl: 'Z drugiego równania $a_{1}=\\frac{8}{q}$ (przy $q\\neq 0$). Podstawiamy: $\\frac{8(1+q^{2})}{q}=20$.', en: 'From the second equation $a_{1}=\\frac{8}{q}$ (with $q\\neq 0$). Substituting: $\\frac{8(1+q^{2})}{q}=20$.' },
            { pl: 'Po pomnożeniu przez $q$: $8q^{2}-20q+8=0$, czyli $2q^{2}-5q+2=0$.', en: 'Multiplying by $q$: $8q^{2}-20q+8=0$, i.e. $2q^{2}-5q+2=0$.' },
            { pl: '$\\Delta=25-16=9$, więc $q=\\frac{5+3}{4}=2$ lub $q=\\frac{5-3}{4}=\\frac{1}{2}$. Odpowiednio $a_{1}=4$ oraz $a_{1}=16$; oba układy sprawdzają się w warunkach zadania.', en: '$\\Delta=25-16=9$, so $q=\\frac{5+3}{4}=2$ or $q=\\frac{5-3}{4}=\\frac{1}{2}$. Correspondingly $a_{1}=4$ and $a_{1}=16$; both satisfy the conditions.' },
          ],
          trap: { pl: 'Zatrzymanie się na jednym pierwiastku. Układ jest symetryczny względem zamiany $q\\leftrightarrow\\frac{1}{q}$ (wyrazy $4,8,16$ i $16,8,4$ to ten sam zbiór w odwrotnej kolejności), więc rozwiązania są dwa i oba trzeba wypisać.', en: 'Stopping at one root. The system is symmetric under $q\\leftrightarrow\\frac{1}{q}$ (the terms $4,8,16$ and $16,8,4$ are the same set reversed), so there are two solutions and both must be given.' },
        },
        {
          id: 'ciag-geometryczny-l4-08',
          skill: 'geom-zadania-tekstowe',
          level: 4,
          prompt: { pl: 'Piłkę spuszczono z wysokości $2$ m. Po każdym odbiciu od podłoża wznosi się ona na wysokość równą $\\frac{3}{4}$ wysokości poprzedniej. Na jaką wysokość wzniesie się piłka po piątym odbiciu? Podaj wynik w metrach.', en: 'A ball is dropped from a height of $2$ m. After each bounce it rises to $\\frac{3}{4}$ of the previous height. To what height does the ball rise after the fifth bounce? Give the answer in metres.' },
          answer: '\\frac{243}{512}',
          accept: ['2\\cdot\\left(\\frac{3}{4}\\right)^{5}', '0.474609375'],
          solution: [
            { pl: 'Wysokości po kolejnych odbiciach tworzą ciąg geometryczny o ilorazie $q=\\frac{3}{4}$.', en: 'The heights after successive bounces form a geometric sequence with ratio $q=\\frac{3}{4}$.' },
            { pl: 'Po pierwszym odbiciu wysokość wynosi $2\\cdot\\frac{3}{4}$, więc po piątym jest to $2\\cdot\\left(\\frac{3}{4}\\right)^{5}$.', en: 'After the first bounce the height is $2\\cdot\\frac{3}{4}$, so after the fifth it is $2\\cdot\\left(\\frac{3}{4}\\right)^{5}$.' },
            { pl: '$\\left(\\frac{3}{4}\\right)^{5}=\\frac{243}{1024}$, zatem wysokość wynosi $\\frac{486}{1024}=\\frac{243}{512}$ metra.', en: '$\\left(\\frac{3}{4}\\right)^{5}=\\frac{243}{1024}$, so the height is $\\frac{486}{1024}=\\frac{243}{512}$ of a metre.' },
          ],
          trap: { pl: 'Użycie wykładnika $4$ przez potraktowanie wysokości początkowej jako „pierwszego odbicia". Wysokość $2$ m jest wysokością przed jakimkolwiek odbiciem, więc po piątym odbiciu wykładnik wynosi $5$.', en: 'Using exponent $4$ by treating the initial height as the "first bounce". The height of $2$ m is the height before any bounce, so after the fifth bounce the exponent is $5$.' },
        },
        {
          id: 'ciag-geometryczny-l5-09',
          skill: 'geom-suma-n-wyrazow',
          level: 5,
          prompt: { pl: 'W skończonym ciągu geometrycznym o $2n$ wyrazach suma wszystkich wyrazów jest pięć razy większa od sumy wyrazów o numerach nieparzystych. Wyznacz iloraz tego ciągu.', en: 'In a finite geometric sequence with $2n$ terms the sum of all terms is five times the sum of the terms with odd indices. Find the ratio of the sequence.' },
          answer: 'q=4',
          accept: ['4'],
          solution: [
            { pl: 'Oznaczmy przez $N$ sumę wyrazów o numerach nieparzystych: $N=a_{1}+a_{3}+\\dots+a_{2n-1}$.', en: 'Let $N$ denote the sum of the odd-indexed terms: $N=a_{1}+a_{3}+\\dots+a_{2n-1}$.' },
            { pl: 'Każdy wyraz o numerze parzystym powstaje z poprzedniego przez pomnożenie przez $q$, więc suma wyrazów parzystych to $a_{2}+a_{4}+\\dots+a_{2n}=qN$.', en: 'Each even-indexed term arises from the preceding one by multiplying by $q$, so the sum of even-indexed terms is $a_{2}+a_{4}+\\dots+a_{2n}=qN$.' },
            { pl: 'Suma wszystkich wyrazów wynosi zatem $S=N+qN=N(1+q)$.', en: 'The sum of all terms is therefore $S=N+qN=N(1+q)$.' },
            { pl: 'Warunek $S=5N$ przy $N\\neq 0$ daje $1+q=5$, czyli $q=4$.', en: 'The condition $S=5N$ with $N\\neq 0$ gives $1+q=5$, i.e. $q=4$.' },
          ],
          trap: { pl: 'Rozpisywanie obu sum wzorem na $S_{n}$ z ilorazem $q^{2}$ i grzęźnięcie w rachunkach zamiast zauważenia, że podciąg parzysty jest po prostu $q$-krotnością nieparzystego. Osobna pułapka językowa: „wyrazy o numerach nieparzystych" to $a_{1},a_{3},\\dots$, a nie wyrazy będące liczbami nieparzystymi.', en: 'Expanding both sums with the $S_{n}$ formula and ratio $q^{2}$, and drowning in algebra instead of noticing that the even subsequence is simply $q$ times the odd one. A separate wording trap: "terms with odd indices" means $a_{1},a_{3},\\dots$, not terms that are odd numbers.' },
        },
      ],
    },

    /* ═══ 4. szereg geometryczny zbieżny ═════════════════════════════════ */
    {
      id: 'szereg-geometryczny',
      title: { pl: 'Szereg geometryczny zbieżny', en: 'Convergent geometric series' },
      level: 4,
      prereq: ['ciag-geometryczny'],
      theory: {
        pl: 'Szereg geometryczny to formalna suma wszystkich wyrazów ciągu geometrycznego, a jego sumą nazywamy granicę ciągu sum częściowych $S_{n}$. Ponieważ $S_{n}=a_{1}\\frac{1-q^{n}}{1-q}$, a $q^{n}\\to 0$ dokładnie wtedy, gdy $|q|<1$, szereg jest zbieżny wtedy i tylko wtedy, gdy $|q|<1$ lub $a_{1}=0$. Ten drugi przypadek wygląda na formalność, ale to on decyduje o punktach w zadaniach z parametrem — szereg złożony z samych zer jest zbieżny niezależnie od $q$, a przy dzieleniu równania przez $a_{1}$ ten pierwiastek znika bez śladu. Suma zbieżnego szeregu wynosi $S=\\frac{a_{1}}{1-q}$. Najczęstsze zastosowania to zamiana ułamka okresowego na zwykły, nieskończone konstrukcje geometryczne (kwadraty i trójkąty wpisywane jedne w drugie) oraz równania, w których szereg stoi po jednej stronie. W tych ostatnich dziedzina $|q|<1$ jest częścią zadania i pierwiastki spoza niej trzeba odrzucić — bo poza nią szereg po prostu nie ma sumy.',
        en: 'A geometric series is the formal sum of all terms of a geometric sequence, and its sum is defined as the limit of the sequence of partial sums $S_{n}$. Since $S_{n}=a_{1}\\frac{1-q^{n}}{1-q}$ and $q^{n}\\to 0$ exactly when $|q|<1$, the series converges if and only if $|q|<1$ or $a_{1}=0$. The second case looks like a formality, but it is what decides marks in parameter problems — a series of all zeros converges regardless of $q$, and dividing the equation by $a_{1}$ makes that root vanish without trace. The sum of a convergent series is $S=\\frac{a_{1}}{1-q}$. The commonest applications are converting a repeating decimal into a fraction, infinite geometric constructions (squares and triangles inscribed one in another), and equations with a series on one side. In the last of these the domain $|q|<1$ is part of the problem and roots outside it must be rejected — outside it the series simply has no sum.',
      },
      formulas: [
        {
          id: 'szereg-warunek-zbieznosci',
          tex: '|q|<1\\ \\lor\\ a_{1}=0',
          name: { pl: 'Warunek zbieżności szeregu geometrycznego', en: 'Convergence condition for a geometric series' },
          note: { pl: 'Przypadek $a_{1}=0$ jest częścią warunku, nie ciekawostką: szereg samych zer jest zbieżny przy dowolnym $q$. Pomijanie go kosztuje punkt w każdym zadaniu z parametrem.', en: 'The case $a_{1}=0$ is part of the condition, not a curiosity: a series of all zeros converges for any $q$. Omitting it costs a mark in every parameter problem.' },
          drill: true,
        },
        {
          id: 'szereg-suma',
          tex: 'S=\\frac{a_{1}}{1-q},\\qquad |q|<1',
          name: { pl: 'Suma zbieżnego szeregu geometrycznego', en: 'Sum of a convergent geometric series' },
          note: { pl: 'W mianowniku $1-q$, a nie $q-1$. Przy $q<0$ mianownik jest większy od $1$, więc suma jest mniejsza od $a_{1}$ — dobry test sensowności wyniku.', en: 'The denominator is $1-q$, not $q-1$. For $q<0$ the denominator exceeds $1$, so the sum is smaller than $a_{1}$ — a good sanity check.' },
          drill: true,
        },
        {
          id: 'szereg-jako-granica',
          tex: 'S=\\lim_{n\\to\\infty}S_{n}=\\lim_{n\\to\\infty}a_{1}\\cdot\\frac{1-q^{n}}{1-q}',
          name: { pl: 'Suma szeregu jako granica sum częściowych', en: 'The sum of a series as the limit of partial sums' },
          note: { pl: 'To jest definicja, a wzór $\\frac{a_{1}}{1-q}$ jest jej konsekwencją: przy $|q|<1$ mamy $q^{n}\\to 0$ i nawias dąży do $1$.', en: 'This is the definition, and the formula $\\frac{a_{1}}{1-q}$ is its consequence: for $|q|<1$ we have $q^{n}\\to 0$ and the bracket tends to $1$.' },
          drill: true,
        },
        {
          id: 'szereg-ulamek-okresowy',
          tex: '0,(d_{1}d_{2}\\dots d_{k})=\\frac{\\overline{d_{1}d_{2}\\dots d_{k}}}{10^{k}-1}',
          name: { pl: 'Ułamek okresowy jako suma szeregu', en: 'A repeating decimal as the sum of a series' },
          note: { pl: 'W mianowniku tyle dziewiątek, ile cyfr liczy okres. Jeśli przed okresem stoją cyfry nieokresowe, trzeba je odciąć osobno — wzór dotyczy wyłącznie okresu zaczynającego się tuż po przecinku.', en: 'The denominator has as many nines as the period has digits. If non-repeating digits precede the period they must be separated out — the formula applies only to a period starting right after the decimal point.' },
          drill: true,
        },
        {
          id: 'szereg-reszta',
          tex: 'a_{n+1}+a_{n+2}+\\dots=\\frac{a_{1}q^{n}}{1-q},\\qquad |q|<1',
          name: { pl: 'Suma ogona szeregu', en: 'Sum of the tail of a series' },
          note: { pl: 'Ogon jest sam w sobie szeregiem geometrycznym o tym samym ilorazie i pierwszym wyrazie $a_{n+1}=a_{1}q^{n}$. Stąd też $S-S_{n}=\\frac{a_{1}q^{n}}{1-q}$.', en: 'The tail is itself a geometric series with the same ratio and first term $a_{n+1}=a_{1}q^{n}$. Hence also $S-S_{n}=\\frac{a_{1}q^{n}}{1-q}$.' },
          drill: true,
        },
      ],
      skills: [
        { id: 'szereg-obliczanie-sumy', title: { pl: 'Obliczanie sumy szeregu', en: 'Computing the sum of a series' }, levels: [2, 3] },
        { id: 'szereg-warunek-parametr', title: { pl: 'Zbieżność szeregu z parametrem', en: 'Convergence of a series with a parameter' }, levels: [3, 4, 5] },
        { id: 'szereg-ulamek-okresowy-skill', title: { pl: 'Zamiana ułamka okresowego na zwykły', en: 'Converting a repeating decimal to a fraction' }, levels: [2, 3] },
        { id: 'szereg-rownania-z-szeregiem', title: { pl: 'Równania z sumą szeregu', en: 'Equations involving the sum of a series' }, levels: [4, 5] },
        { id: 'szereg-geometria-nieskonczona', title: { pl: 'Nieskończone konstrukcje geometryczne', en: 'Infinite geometric constructions' }, levels: [3, 4, 5] },
      ],
      problems: [
        {
          id: 'szereg-geometryczny-l2-01',
          skill: 'szereg-obliczanie-sumy',
          level: 2,
          prompt: { pl: 'Oblicz sumę szeregu geometrycznego $9+3+1+\\frac{1}{3}+\\dots$', en: 'Compute the sum of the geometric series $9+3+1+\\frac{1}{3}+\\dots$' },
          answer: '\\frac{27}{2}',
          accept: ['13.5', '13\\frac{1}{2}'],
          solution: [
            { pl: 'Mamy $a_{1}=9$ oraz $q=\\frac{3}{9}=\\frac{1}{3}$, a $\\left|\\frac{1}{3}\\right|<1$, więc szereg jest zbieżny.', en: 'We have $a_{1}=9$ and $q=\\frac{3}{9}=\\frac{1}{3}$, and $\\left|\\frac{1}{3}\\right|<1$, so the series converges.' },
            { pl: '$S=\\frac{a_{1}}{1-q}=\\frac{9}{1-\\frac{1}{3}}=\\frac{9}{\\frac{2}{3}}$.', en: '$S=\\frac{a_{1}}{1-q}=\\frac{9}{1-\\frac{1}{3}}=\\frac{9}{\\frac{2}{3}}$.' },
            { pl: '$S=9\\cdot\\frac{3}{2}=\\frac{27}{2}$.', en: '$S=9\\cdot\\frac{3}{2}=\\frac{27}{2}$.' },
          ],
          trap: { pl: 'Użycie wzoru na $S_{n}$ dla skończonej liczby wyrazów zamiast $\\frac{a_{1}}{1-q}$, albo obliczenie $\\frac{9}{1-\\frac{1}{3}}$ jako $9\\cdot\\frac{2}{3}=6$ — dzielenie przez ułamek to mnożenie przez odwrotność.', en: 'Using the finite $S_{n}$ formula instead of $\\frac{a_{1}}{1-q}$, or evaluating $\\frac{9}{1-\\frac{1}{3}}$ as $9\\cdot\\frac{2}{3}=6$ — dividing by a fraction means multiplying by its reciprocal.' },
        },
        {
          id: 'szereg-geometryczny-l2-02',
          skill: 'szereg-ulamek-okresowy-skill',
          level: 2,
          prompt: { pl: 'Zapisz liczbę $0,(36)$ w postaci ułamka zwykłego nieskracalnego.', en: 'Write the number $0.(36)$ as a fraction in lowest terms.' },
          answer: '\\frac{4}{11}',
          accept: ['\\frac{36}{99}'],
          solution: [
            { pl: '$0,(36)=\\frac{36}{100}+\\frac{36}{10000}+\\dots$ — szereg geometryczny o $a_{1}=\\frac{36}{100}$ i $q=\\frac{1}{100}$.', en: '$0.(36)=\\frac{36}{100}+\\frac{36}{10000}+\\dots$ — a geometric series with $a_{1}=\\frac{36}{100}$ and $q=\\frac{1}{100}$.' },
            { pl: '$S=\\frac{\\frac{36}{100}}{1-\\frac{1}{100}}=\\frac{\\frac{36}{100}}{\\frac{99}{100}}=\\frac{36}{99}$.', en: '$S=\\frac{\\frac{36}{100}}{1-\\frac{1}{100}}=\\frac{\\frac{36}{100}}{\\frac{99}{100}}=\\frac{36}{99}$.' },
            { pl: 'Skracamy przez $9$: $\\frac{36}{99}=\\frac{4}{11}$.', en: 'Cancel by $9$: $\\frac{36}{99}=\\frac{4}{11}$.' },
          ],
          trap: { pl: 'Napisanie $\\frac{36}{100}$ albo $\\frac{36}{90}$. Liczba dziewiątek w mianowniku równa się liczbie cyfr okresu — tutaj okres ma dwie cyfry, więc mianownik to $99$.', en: 'Writing $\\frac{36}{100}$ or $\\frac{36}{90}$. The number of nines equals the number of digits in the period — here the period has two digits, so the denominator is $99$.' },
        },
        {
          id: 'szereg-geometryczny-l3-03',
          skill: 'szereg-ulamek-okresowy-skill',
          level: 3,
          prompt: { pl: 'Zapisz liczbę $0,2(7)$ w postaci ułamka zwykłego nieskracalnego.', en: 'Write the number $0.2(7)$ as a fraction in lowest terms.' },
          answer: '\\frac{5}{18}',
          accept: ['\\frac{25}{90}'],
          solution: [
            { pl: 'Rozbijamy: $0,2(7)=0,2+(0,07+0,007+0,0007+\\dots)$, bo okres zaczyna się dopiero na drugim miejscu po przecinku.', en: 'Split it: $0.2(7)=0.2+(0.07+0.007+0.0007+\\dots)$, since the period starts only at the second decimal place.' },
            { pl: 'Nawias to szereg geometryczny o $a_{1}=\\frac{7}{100}$ i $q=\\frac{1}{10}$, więc jego suma wynosi $\\frac{\\frac{7}{100}}{\\frac{9}{10}}=\\frac{7}{90}$.', en: 'The bracket is a geometric series with $a_{1}=\\frac{7}{100}$ and $q=\\frac{1}{10}$, so its sum is $\\frac{\\frac{7}{100}}{\\frac{9}{10}}=\\frac{7}{90}$.' },
            { pl: '$0,2(7)=\\frac{1}{5}+\\frac{7}{90}=\\frac{18}{90}+\\frac{7}{90}=\\frac{25}{90}=\\frac{5}{18}$.', en: '$0.2(7)=\\frac{1}{5}+\\frac{7}{90}=\\frac{18}{90}+\\frac{7}{90}=\\frac{25}{90}=\\frac{5}{18}$.' },
          ],
          trap: { pl: 'Potraktowanie zapisu jak $0,(27)$ i napisanie $\\frac{27}{99}$. Cyfra $2$ nie należy do okresu, więc pierwszym wyrazem szeregu jest $\\frac{7}{100}$, a nie $\\frac{27}{100}$, i część nieokresową trzeba dodać osobno.', en: 'Reading the notation as $0.(27)$ and writing $\\frac{27}{99}$. The digit $2$ is not part of the period, so the first term of the series is $\\frac{7}{100}$, not $\\frac{27}{100}$, and the non-repeating part must be added separately.' },
        },
        {
          id: 'szereg-geometryczny-l3-04',
          skill: 'szereg-obliczanie-sumy',
          level: 3,
          prompt: { pl: 'Oblicz sumę szeregu geometrycznego $8-4+2-1+\\dots$', en: 'Compute the sum of the geometric series $8-4+2-1+\\dots$' },
          answer: '\\frac{16}{3}',
          accept: ['5\\frac{1}{3}'],
          solution: [
            { pl: 'Iloraz wynosi $q=\\frac{-4}{8}=-\\frac{1}{2}$, a $\\left|-\\frac{1}{2}\\right|<1$, więc szereg jest zbieżny.', en: 'The ratio is $q=\\frac{-4}{8}=-\\frac{1}{2}$, and $\\left|-\\frac{1}{2}\\right|<1$, so the series converges.' },
            { pl: '$S=\\frac{8}{1-\\left(-\\frac{1}{2}\\right)}=\\frac{8}{\\frac{3}{2}}$.', en: '$S=\\frac{8}{1-\\left(-\\frac{1}{2}\\right)}=\\frac{8}{\\frac{3}{2}}$.' },
            { pl: '$S=8\\cdot\\frac{2}{3}=\\frac{16}{3}$.', en: '$S=8\\cdot\\frac{2}{3}=\\frac{16}{3}$.' },
          ],
          trap: { pl: 'Przyjęcie $q=\\frac{1}{2}$ i zignorowanie znaków, co daje $16$. Podwójny minus w mianowniku, $1-\\left(-\\frac{1}{2}\\right)=\\frac{3}{2}$, jest tu całą treścią zadania.', en: 'Taking $q=\\frac{1}{2}$ and ignoring the signs, which gives $16$. The double minus in the denominator, $1-\\left(-\\frac{1}{2}\\right)=\\frac{3}{2}$, is the whole point of the problem.' },
        },
        {
          id: 'szereg-geometryczny-l3-05',
          skill: 'szereg-geometria-nieskonczona',
          level: 3,
          prompt: { pl: 'W kwadrat o boku $a$ wpisano kwadrat, łącząc środki jego kolejnych boków. W otrzymany kwadrat wpisano w ten sam sposób następny i tak dalej w nieskończoność. Oblicz sumę pól wszystkich tych kwadratów.', en: 'A square is inscribed in a square of side $a$ by joining the midpoints of its consecutive sides. Another square is inscribed in the resulting one in the same way, and so on indefinitely. Compute the sum of the areas of all these squares.' },
          answer: '2a^{2}',
          accept: [],
          solution: [
            { pl: 'Bok kolejnego kwadratu to przeciwprostokątna trójkąta o przyprostokątnych $\\frac{a}{2}$, czyli $\\frac{a\\sqrt{2}}{2}$.', en: 'The side of the next square is the hypotenuse of a triangle with legs $\\frac{a}{2}$, i.e. $\\frac{a\\sqrt{2}}{2}$.' },
            { pl: 'Pole kolejnego kwadratu wynosi $\\left(\\frac{a\\sqrt{2}}{2}\\right)^{2}=\\frac{a^{2}}{2}$, więc pola tworzą ciąg geometryczny o ilorazie $q=\\frac{1}{2}$.', en: 'Its area is $\\left(\\frac{a\\sqrt{2}}{2}\\right)^{2}=\\frac{a^{2}}{2}$, so the areas form a geometric sequence with ratio $q=\\frac{1}{2}$.' },
            { pl: 'Pierwszym wyrazem jest $a^{2}$, zatem $S=\\frac{a^{2}}{1-\\frac{1}{2}}=2a^{2}$.', en: 'The first term is $a^{2}$, hence $S=\\frac{a^{2}}{1-\\frac{1}{2}}=2a^{2}$.' },
          ],
          trap: { pl: 'Wzięcie za iloraz stosunku boków $\\frac{\\sqrt{2}}{2}$ zamiast stosunku pól $\\frac{1}{2}$. Przy skalowaniu figury o współczynnik $k$ pole zmienia się o $k^{2}$ — pytanie dotyczy pól, więc iloraz podnosi się do kwadratu.', en: 'Taking the side ratio $\\frac{\\sqrt{2}}{2}$ as the common ratio instead of the area ratio $\\frac{1}{2}$. Scaling a figure by $k$ scales its area by $k^{2}$ — the question is about areas, so the ratio gets squared.' },
        },
        {
          id: 'szereg-geometryczny-l4-06',
          skill: 'szereg-geometria-nieskonczona',
          level: 4,
          prompt: { pl: 'W trójkąt równoboczny o boku $a$ wpisano trójkąt równoboczny, łącząc środki jego boków, i powtórzono tę konstrukcję nieskończenie wiele razy. Oblicz sumę obwodów wszystkich otrzymanych trójkątów (łącznie z wyjściowym).', en: 'An equilateral triangle is inscribed in an equilateral triangle of side $a$ by joining the midpoints of its sides, and the construction is repeated infinitely many times. Compute the sum of the perimeters of all the triangles obtained (including the original one).' },
          answer: '6a',
          accept: [],
          solution: [
            { pl: 'Odcinek łączący środki dwóch boków jest równoległy do trzeciego boku i ma połowę jego długości, więc bok kolejnego trójkąta wynosi $\\frac{a}{2}$.', en: 'The segment joining the midpoints of two sides is parallel to the third and half its length, so the side of the next triangle is $\\frac{a}{2}$.' },
            { pl: 'Obwody tworzą ciąg geometryczny o $a_{1}=3a$ i $q=\\frac{1}{2}$.', en: 'The perimeters form a geometric sequence with $a_{1}=3a$ and $q=\\frac{1}{2}$.' },
            { pl: '$S=\\frac{3a}{1-\\frac{1}{2}}=6a$.', en: '$S=\\frac{3a}{1-\\frac{1}{2}}=6a$.' },
          ],
          trap: { pl: 'Użycie ilorazu $\\frac{1}{4}$, właściwego dla pól, przy pytaniu o obwody. Obwód skaluje się liniowo, więc iloraz to $\\frac{1}{2}$; wynik z $\\frac{1}{4}$ daje $4a$ i jest fałszywy.', en: 'Using the ratio $\\frac{1}{4}$, which belongs to areas, in a question about perimeters. Perimeter scales linearly, so the ratio is $\\frac{1}{2}$; the answer from $\\frac{1}{4}$ would be $4a$ and is wrong.' },
        },
        {
          id: 'szereg-geometryczny-l4-07',
          skill: 'szereg-warunek-parametr',
          level: 4,
          prompt: { pl: 'Wyznacz wszystkie wartości $x$, dla których szereg $1+(x-2)+(x-2)^{2}+(x-2)^{3}+\\dots$ jest zbieżny, i podaj jego sumę.', en: 'Find all $x$ for which the series $1+(x-2)+(x-2)^{2}+(x-2)^{3}+\\dots$ converges, and give its sum.' },
          answer: 'x\\in(1,3),\\ S=\\frac{1}{3-x}',
          accept: ['x\\in(1,3),\\ S=\\frac{1}{1-(x-2)}'],
          solution: [
            { pl: 'Mamy $a_{1}=1\\neq 0$ oraz $q=x-2$, więc warunkiem zbieżności jest $|x-2|<1$.', en: 'Here $a_{1}=1\\neq 0$ and $q=x-2$, so the convergence condition is $|x-2|<1$.' },
            { pl: 'Nierówność $|x-2|<1$ oznacza $-1<x-2<1$, czyli $1<x<3$.', en: 'The inequality $|x-2|<1$ means $-1<x-2<1$, i.e. $1<x<3$.' },
            { pl: 'Dla takich $x$ suma wynosi $S=\\frac{1}{1-(x-2)}=\\frac{1}{3-x}$.', en: 'For such $x$ the sum is $S=\\frac{1}{1-(x-2)}=\\frac{1}{3-x}$.' },
          ],
          trap: { pl: 'Rozwiązanie nierówności $x-2<1$ bez wartości bezwzględnej, co daje $x<3$ i błędnie dopuszcza na przykład $x=0$ (wtedy $q=-2$ i szereg jest rozbieżny). Drugi błąd to uproszczenie $1-(x-2)$ do $1-x-2$.', en: 'Solving $x-2<1$ without the absolute value, which gives $x<3$ and wrongly admits e.g. $x=0$ (where $q=-2$ and the series diverges). A second error is simplifying $1-(x-2)$ to $1-x-2$.' },
        },
        {
          id: 'szereg-geometryczny-l5-08',
          skill: 'szereg-rownania-z-szeregiem',
          level: 5,
          prompt: { pl: 'Rozwiąż równanie $x+x^{2}+x^{3}+x^{4}+\\dots=2-x$, w którym lewa strona jest sumą zbieżnego szeregu geometrycznego.', en: 'Solve the equation $x+x^{2}+x^{3}+x^{4}+\\dots=2-x$, where the left-hand side is the sum of a convergent geometric series.' },
          answer: 'x=2-\\sqrt{2}',
          accept: [],
          solution: [
            { pl: 'Lewa strona to szereg o $a_{1}=x$ i $q=x$; jest zbieżny dla $|x|<1$ (przypadek $x=0$ daje sumę $0\\neq 2$, więc odpada).', en: 'The left side is a series with $a_{1}=x$ and $q=x$; it converges for $|x|<1$ (the case $x=0$ gives sum $0\\neq 2$, so it is out).' },
            { pl: 'Dla $|x|<1$ suma wynosi $\\frac{x}{1-x}$, więc równanie to $\\frac{x}{1-x}=2-x$.', en: 'For $|x|<1$ the sum is $\\frac{x}{1-x}$, so the equation reads $\\frac{x}{1-x}=2-x$.' },
            { pl: 'Mnożymy przez $1-x\\neq 0$: $x=(2-x)(1-x)=x^{2}-3x+2$, czyli $x^{2}-4x+2=0$.', en: 'Multiply by $1-x\\neq 0$: $x=(2-x)(1-x)=x^{2}-3x+2$, i.e. $x^{2}-4x+2=0$.' },
            { pl: '$\\Delta=16-8=8$, więc $x=2-\\sqrt{2}$ lub $x=2+\\sqrt{2}$. Ponieważ $2+\\sqrt{2}\\approx 3{,}41$ nie spełnia $|x|<1$, odrzucamy je; zostaje $x=2-\\sqrt{2}\\approx 0{,}59$.', en: '$\\Delta=16-8=8$, so $x=2-\\sqrt{2}$ or $x=2+\\sqrt{2}$. Since $2+\\sqrt{2}\\approx 3.41$ fails $|x|<1$, it is rejected; this leaves $x=2-\\sqrt{2}\\approx 0.59$.' },
            { pl: 'Sprawdzenie: $\\frac{2-\\sqrt{2}}{1-(2-\\sqrt{2})}=\\frac{2-\\sqrt{2}}{\\sqrt{2}-1}=\\sqrt{2}$ oraz $2-(2-\\sqrt{2})=\\sqrt{2}$.', en: 'Check: $\\frac{2-\\sqrt{2}}{1-(2-\\sqrt{2})}=\\frac{2-\\sqrt{2}}{\\sqrt{2}-1}=\\sqrt{2}$ and $2-(2-\\sqrt{2})=\\sqrt{2}$.' },
          ],
          trap: { pl: 'Podanie obu pierwiastków równania kwadratowego. Dziedziną zadania jest $|x|<1$, bo tylko tam szereg w ogóle ma sumę — dla $x=2+\\sqrt{2}$ lewa strona nie jest liczbą i podstawienie do wzoru $\\frac{a_{1}}{1-q}$ jest bezprawne.', en: 'Giving both roots of the quadratic. The domain of the problem is $|x|<1$, since only there does the series have a sum at all — for $x=2+\\sqrt{2}$ the left side is not a number and substituting into $\\frac{a_{1}}{1-q}$ is illegitimate.' },
        },
        {
          id: 'szereg-geometryczny-l5-09',
          skill: 'szereg-rownania-z-szeregiem',
          level: 5,
          prompt: { pl: 'W pewnym zbieżnym szeregu geometrycznym suma wszystkich wyrazów wynosi $16$, a suma wyrazów o numerach parzystych jest równa $-\\frac{16}{3}$. Wyznacz pierwszy wyraz i iloraz tego szeregu.', en: 'In a convergent geometric series the sum of all terms is $16$ and the sum of the terms with even indices equals $-\\frac{16}{3}$. Find the first term and the ratio of the series.' },
          answer: 'a_{1}=20,\\ q=-\\frac{1}{4}',
          accept: ['(a_{1},q)=\\left(20,-\\frac{1}{4}\\right)'],
          solution: [
            { pl: 'Oznaczmy przez $N$ sumę wyrazów o numerach nieparzystych, a przez $P$ sumę wyrazów o numerach parzystych. Każdy wyraz parzysty jest $q$-krotnością poprzedzającego go nieparzystego, więc $P=qN$.', en: 'Let $N$ be the sum of the odd-indexed terms and $P$ the sum of the even-indexed ones. Each even-indexed term is $q$ times the odd-indexed term before it, so $P=qN$.' },
            { pl: 'Z $N+P=16$ i $P=-\\frac{16}{3}$ mamy $N=16+\\frac{16}{3}=\\frac{64}{3}$.', en: 'From $N+P=16$ and $P=-\\frac{16}{3}$ we get $N=16+\\frac{16}{3}=\\frac{64}{3}$.' },
            { pl: 'Zatem $q=\\frac{P}{N}=\\frac{-\\frac{16}{3}}{\\frac{64}{3}}=-\\frac{1}{4}$, i istotnie $\\left|-\\frac{1}{4}\\right|<1$.', en: 'Hence $q=\\frac{P}{N}=\\frac{-\\frac{16}{3}}{\\frac{64}{3}}=-\\frac{1}{4}$, and indeed $\\left|-\\frac{1}{4}\\right|<1$.' },
            { pl: 'Z $S=\\frac{a_{1}}{1-q}$ mamy $a_{1}=S(1-q)=16\\cdot\\frac{5}{4}=20$.', en: 'From $S=\\frac{a_{1}}{1-q}$ we get $a_{1}=S(1-q)=16\\cdot\\frac{5}{4}=20$.' },
          ],
          trap: { pl: 'Przyjęcie, że podszereg wyrazów parzystych ma iloraz $q$ — ma iloraz $q^{2}$, bo kolejne jego wyrazy to $a_{2},a_{4},a_{6},\\dots$. Prawdziwa jest natomiast relacja $P=qN$ między całymi sumami i to ona rozwiązuje zadanie w dwóch linijkach.', en: 'Assuming the even-indexed subseries has ratio $q$ — its ratio is $q^{2}$, since its successive terms are $a_{2},a_{4},a_{6},\\dots$. What is true is the relation $P=qN$ between the whole sums, and that is what solves the problem in two lines.' },
        },
      ],
    },
    /* __MORE__ */
  ],
};
