// Checks the FSRS-6 port against golden vectors generated by the reference
// implementation (py-fsrs). Regenerate with tools/gen-golden.py if the
// reference ever changes.
//   node tools/srs.test.mjs
import fs from 'node:fs';
import path from 'node:path';
import { Scheduler, STATE, RATING, DEFAULT_PARAMETERS } from '../public/js/srs.js';

const golden = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'tools', 'fsrs-golden.json'), 'utf8'));

let failures = 0;
let checks = 0;

function near(actual, expected, label, tol = 1e-9) {
  checks += 1;
  if (expected === null || actual === null) {
    if (actual !== expected) {
      failures += 1;
      console.error(`  FAIL ${label}: got ${actual}, want ${expected}`);
    }
    return;
  }
  const diff = Math.abs(actual - expected);
  const scale = Math.max(1, Math.abs(expected));
  if (diff / scale > tol) {
    failures += 1;
    console.error(`  FAIL ${label}: got ${actual}, want ${expected} (diff ${diff})`);
  }
}

function eq(actual, expected, label) {
  checks += 1;
  if (actual !== expected) {
    failures += 1;
    console.error(`  FAIL ${label}: got ${JSON.stringify(actual)}, want ${JSON.stringify(expected)}`);
  }
}

/* ---- constants ---- */
console.log('parameters');
eq(DEFAULT_PARAMETERS.length, golden.params.length, 'parameter count');
golden.params.forEach((p, i) => near(DEFAULT_PARAMETERS[i], p, `w${i}`));

const s = new Scheduler({ enableFuzzing: false });
near(s.DECAY, golden.decay, 'DECAY');
near(s.FACTOR, golden.factor, 'FACTOR');

// The mean-reversion target must stay unclamped and negative.
near(s.initialDifficulty(RATING.EASY, false), -4.7716307031617, 'unclamped D0(Easy)', 1e-9);
eq(s.initialDifficulty(RATING.EASY, true), 1.0, 'clamped D0(Easy) hits the floor');

/* ---- scheduling sequences ---- */
const t0 = Date.parse(golden.t0);

for (const { seq, steps } of golden.sequences) {
  console.log(`sequence ${seq.join(',')}`);
  let card = {
    id: 'test',
    state: STATE.LEARNING,
    step: 0,
    stability: null,
    difficulty: null,
    due: t0,
    lastReview: null,
    reps: 0,
    lapses: 0,
  };
  let now = t0;
  steps.forEach((want, i) => {
    now = Math.max(now, card.due);
    eq(new Date(now).toISOString().replace('.000Z', '+00:00'), want.at, `  step ${i} review time`);
    ({ card } = s.review(card, want.rating, now));
    near(card.stability, want.stability, `  step ${i} stability`, 1e-9);
    near(card.difficulty, want.difficulty, `  step ${i} difficulty`, 1e-9);
    eq(card.state, want.state, `  step ${i} state`);
    eq(card.step, want.step, `  step ${i} step`);
    // Reference rounds intervals to whole days once out of learning; allow a
    // millisecond of float drift, nothing more.
    near(card.due - t0, want.dueOffsetMs, `  step ${i} due offset`, 1e-9);
  });
}

/* ---- retrievability ---- */
console.log('retrievability');
const mature = {
  id: 'm',
  state: golden.matureCard.state,
  step: null,
  stability: golden.matureCard.stability,
  difficulty: golden.matureCard.difficulty,
  lastReview: t0,
  due: t0,
  reps: 3,
  lapses: 0,
};
for (const { days, r } of golden.retrievability) {
  near(s.retrievability(mature, t0 + days * 86400000), r, `  R at ${days}d`, 1e-9);
}

/* ---- fuzz stays inside its band ---- */
console.log('fuzz');
const fz = new Scheduler({ enableFuzzing: true });
for (const days of [3, 10, 40, 400]) {
  let lo = Infinity;
  let hi = -Infinity;
  for (let i = 0; i < 400; i++) {
    const out = fz.fuzzIntervalMs(days * 86400000) / 86400000;
    lo = Math.min(lo, out);
    hi = Math.max(hi, out);
  }
  checks += 1;
  if (lo < 2 || hi > days * 1.35 + 2) {
    failures += 1;
    console.error(`  FAIL fuzz ${days}d spread ${lo}..${hi}`);
  }
  // And it must actually vary, or the whole point is lost.
  checks += 1;
  if (lo === hi) {
    failures += 1;
    console.error(`  FAIL fuzz ${days}d produced no variation`);
  }
}

console.log(`\n${checks - failures}/${checks} checks passed`);
if (failures) {
  console.error(`${failures} FAILURES`);
  process.exit(1);
}
console.log('FSRS-6 port matches the reference implementation.');
